# For more easy access in a composed environment, you have to access the docs at http://localhost/docs
FROM gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas
MAINTAINER Tobias Krauhoff <krauthoff@cs.uni-duesseldorf.de>

WORKDIR /dbas/docs

RUN apk add --no-cache install make && \
    make html

WORKDIR /dbas/docs/_build/html/

RUN mkdir -p docs && \
    mv * docs || true

EXPOSE 8000
CMD ["python", "-m", "http.server", "8000"]
