"""Add author_uid to statement origins

Revision ID: 015a354d1b3d
Revises: 017a0dd30585
Create Date: 2018-10-29 07:39:51.711121

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '015a354d1b3d'
down_revision = '017a0dd30585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_origins', sa.Column('author_uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'statement_origins', 'users', ['author_uid'], ['uid'])
    op.drop_column('statement_origins', 'author')
    op.alter_column('statement_to_issue', 'issue_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statement_to_issue', 'statement_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statement_to_issue', 'statement_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statement_to_issue', 'issue_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('statement_origins', sa.Column('author', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'statement_origins', type_='foreignkey')
    op.drop_column('statement_origins', 'author_uid')
    # ### end Alembic commands ###
