"""Add UserParticipation table

Revision ID: 017a0dd30585
Revises: c914642d6e58
Create Date: 2018-10-14 11:25:03.460864

"""
# revision identifiers, used by Alembic.
from typing import List

import sqlalchemy as sa
import transaction
from alembic import op

from dbas.database import DBDiscussionSession
from dbas.database.discussion_model import User, Issue

revision = '017a0dd30585'
down_revision = 'c914642d6e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_participation',
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('issue_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_uid'], ['issues.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_uid', 'issue_uid')
    )
    # ### end Alembic commands ###
    DBDiscussionSession.remove()
    DBDiscussionSession.configure(bind=op.get_bind())

    db_users: List[User] = DBDiscussionSession.query(User).all()
    for db_user in db_users:
        issue_slugs = set([history.path.split('/', 2)[1] for history in db_user.history])
        issues: List[Issue] = DBDiscussionSession.query(Issue).filter(Issue.slug.in_(issue_slugs))
        db_user.participates_in.extend(issues)

    transaction.commit()




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_participation')
    # ### end Alembic commands ###
