"""Add decidotron tables

Revision ID: 2a1107018fad
Revises: ed6cbcd62bee
Create Date: 2019-02-16 17:41:15.330449

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a1107018fad'
down_revision = 'ed6cbcd62bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
                    sa.Column('identifier', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('identifier')
                    )
    op.create_table('decidotron_position_cost',
                    sa.Column('position_id', sa.Integer(), nullable=False),
                    sa.Column('cost', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['position_id'], ['statements.uid'], ),
                    sa.PrimaryKeyConstraint('position_id')
                    )
    op.create_table('decidotron_decision_process',
                    sa.Column('issue_id', sa.Integer(), nullable=False),
                    sa.Column('budget', sa.Integer(), nullable=False),
                    sa.Column('currency_symbol', sa.String(), nullable=True),
                    sa.Column('positions_end', sa.DateTime(), nullable=True),
                    sa.Column('votes_end', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['issue_id'], ['issues.uid'], ),
                    sa.PrimaryKeyConstraint('issue_id')
                    )
    op.create_table('issue_features',
                    sa.Column('issue_id', sa.Integer(), nullable=False),
                    sa.Column('feature_identifier', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['feature_identifier'], ['feature.identifier'], ),
                    sa.ForeignKeyConstraint(['issue_id'], ['issues.uid'], ),
                    sa.PrimaryKeyConstraint('issue_id', 'feature_identifier')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_features')
    op.drop_table('decidotron_decision_process')
    op.drop_table('decidotron_position_cost')
    op.drop_table('feature')
    # ### end Alembic commands ###
