"""Rename StatementReference.reference to text

Revision ID: 2f5bfca8d0e5
Revises: 34d1bfb33788
Create Date: 2018-12-04 10:15:49.774159

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2f5bfca8d0e5'
down_revision = '34d1bfb33788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arguments', 'premisegroup_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statement_references', 'reference', nullable=False, new_column_name='text')
    op.alter_column('statements', 'is_position',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'is_position',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('statement_references', 'text', nullable=False, new_column_name='reference')
    op.alter_column('arguments', 'premisegroup_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
