"""Fix author of statement-origin

Revision ID: 34d1bfb33788
Revises: 015a354d1b3d
Create Date: 2018-10-29 09:46:13.158201

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '34d1bfb33788'
down_revision = '015a354d1b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_origins', sa.Column('author', sa.Text(), nullable=True))
    op.drop_constraint('statement_origins_author_uid_fkey', 'statement_origins', type_='foreignkey')
    op.drop_column('statement_origins', 'author_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_origins', sa.Column('author_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('statement_origins_author_uid_fkey', 'statement_origins', 'users', ['author_uid'], ['uid'])
    op.drop_column('statement_origins', 'author')
    # ### end Alembic commands ###
