"""Modify user table to add oauth information

Revision ID: 42d481d084b2
Revises: 2a4bc7c8ff38
Create Date: 2017-11-10 09:59:09.867352

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '42d481d084b2'
down_revision = '2a4bc7c8ff38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
