"""Rename statements position attribute

Revision ID: 45be64188139
Revises: ed3484af5b24
Create Date: 2018-03-13 08:54:17.810933

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '45be64188139'
down_revision = 'ed3484af5b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'is_startpoint', new_column_name='is_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'is_position', new_column_name='is_startpoint')
    # ### end Alembic commands ###
