"""Rename premisesgroup_.. to premisegroup_..

Revision ID: 45f5c1f60de9
Revises: 45be64188139
Create Date: 2018-03-26 08:27:13.189531

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '45f5c1f60de9'
down_revision = '45be64188139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arguments', 'premisesgroup_uid', new_column_name='premisegroup_uid')
    op.alter_column('premises', 'premisesgroup_uid', new_column_name='premisegroup_uid')
    op.alter_column('review_merge', 'premisesgroup_uid', new_column_name='premisegroup_uid')
    op.alter_column('review_split', 'premisesgroup_uid', new_column_name='premisegroup_uid')
    op.alter_column('statements', 'is_position', existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'is_position', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column('review_split', 'premisegroup_uid', new_column_name='premisesgroup_uid')
    op.alter_column('review_merge', 'premisegroup_uid', new_column_name='premisesgroup_uid')
    op.alter_column('premises', 'premisegroup_uid', new_column_name='premisesgroup_uid')
    op.alter_column('arguments', 'premisegroup_uid', new_column_name='premisesgroup_uid')
    # ### end Alembic commands ###
