"""Add Feature flag

Revision ID: 96136afd7cc8
Revises: ed6cbcd62bee
Create Date: 2019-01-23 16:26:49.472978

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '96136afd7cc8'
down_revision = 'ed6cbcd62bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
