"""Add start of voting field

Revision ID: b29af013b432
Revises: 2a1107018fad
Create Date: 2019-03-08 15:07:20.519831

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b29af013b432'
down_revision = '2a1107018fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decidotron_decision_process', sa.Column('votes_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decidotron_decision_process', 'votes_start')
    # ### end Alembic commands ###
