"""Remove RSS table

Revision ID: c914642d6e58
Revises: 6517c5e2b39a
Create Date: 2018-09-15 14:14:37.116113

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c914642d6e58'
down_revision = '6517c5e2b39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss',
                    sa.Column('uid', sa.INTEGER(), nullable=False),
                    sa.Column('author_uid', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('issue_uid', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['author_uid'], ['users.uid'], name='rss_author_uid_fkey'),
                    sa.ForeignKeyConstraint(['issue_uid'], ['issues.uid'], name='rss_issue_uid_fkey'),
                    sa.PrimaryKeyConstraint('uid', name='rss_pkey')
                    )
    # ### end Alembic commands ###
