"""Add statement_origins table

Revision ID: f0bf03bf6326
Revises: ed3484af5b24
Create Date: 2017-11-03 11:56:28.985785

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f0bf03bf6326'
down_revision = '45f5c1f60de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_origins',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('aggregate_id', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('statement_uid', sa.Integer(), nullable=False),
    sa.Column('created', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.ForeignKeyConstraint(['statement_uid'], ['statements.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement_origins')
    # ### end Alembic commands ###
