#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
German translations of the keywords

.. codeauthor:: Tobias Krauthoff <krauthoff@cs.uni-duesseldorf.de
"""
from .keywords import Keywords as _

de_lang = {
    _.arguments: 'Argumente',
    _.error: 'Fehler',
    _.iActuallyHave: 'Ich habe',
    _.insertOneArgument: 'Ich habe ein Argument mit xx Begründungen:',
    _.insertDontCare: 'Übernehme es so, wie es ist',
    _.forgotInputRadio: 'Sie haben eine Auswahl vergessen',
    _.needHelpToUnderstandStatement: 'Wir brauchen Hilfe zum Verständnis Ihrer Aussage',
    _.setPremisegroupsIntro1: 'Sie haben \'und\' in Ihrer Aussage ',
    _.setPremisegroupsIntro2: ' benutzt. Daher existieren mehrere mögliche Auswertungen. Bitte helfen Sie uns, die richtig Eingabe zu wählen:',
    _.attack: 'Sie lehnen ab, dass',
    _.assertion: 'Behauptung',
    _.support: 'Sie akzeptieren',
    _.premise: 'Prämisse',
    _.because: 'Weil',
    _.moreAbout: 'Mehr über',
    _.undermine: 'Es ist falsch, dass',
    _.support1: 'Es ist richtig, dass',
    _.undercut1: 'Es ist falsch, dass',
    _.undercut2: 'und das ist ein schlechter Konter',
    _.rebut1: 'Es ist richtig, dass',
    _.rebut2: ', aber ich habe etwas besseres',
    _.oldPwdEmpty: 'Altes Passwortfeld ist leer',
    _.newPwdEmtpy: 'Neues Passwortfeld ist leer',
    _.confPwdEmpty: 'Bestätigungs-Passwortfeld ist leer',
    _.newPwdNotEqual: 'Neues und altes Passwort stimmen nicht überein',
    _.pwdsSame: 'Das alte und neue Passwort sind identisch',
    _.oldPwdWrong: 'Ihr altes Passwort ist falsch',
    _.pwdChanged: 'Ihr Passwort wurde geändert',
    _.emptyName: 'Ihr Name ist leer',
    _.emptyEmail: 'Ihre E-Mail ist leer',
    _.emtpyContent: 'Ihr Inhalt ist leer',
    _.maliciousAntiSpam: 'Ihr Anti-Spam-Nachricht ist falsch. Bitte laden Sie die Seite neu',
    _.maliciousSlug: 'Fehlerhafte URL',
    _.nonValidCSRF: 'Ihre Sitzung ist abgelaufen',
    _.name: 'Name',
    _.mail: 'Mail',
    _.phone: 'Telefon',
    _.message: 'Nachricht',
    _.messageDeleted: 'Nachricht gelöscht',
    _.notification: 'Benachrichtigung',
    _.notificationDeleted: 'Benachrichtigung gelöscht',
    _.pwdNotEqual: 'Passwörter stimmen nicht überein',
    _.pwdShort: 'Passwort ist zu kurz (min. 5 Zeichen)',
    _.nickIsTaken: 'Benutzername ist schon vergeben',
    _.mailIsTaken: 'E-Mail ist schon vergeben',
    _.mailNotValid: 'E-Mail ist nicht gültig',
    _.mailSettingsTitle: '(De-)Aktiviert E-Mail',
    _.notificationSettingsTitle: '(De-)Aktiviert Nachrichten',
    _.errorTryLateOrContant: 'Leider ist ein Fehler aufgetreten, bitte versuchen Sie später erneut oder kontaktieren Sie uns',
    _.accountWasAdded: 'Ihr Account {} wurde angelegt. Sie können sich nun anmelden',
    _.accountRegistration: 'D-BAS Registrierung',
    _.accountWasRegistered: 'Hi {} {},\n\nein Account wurde erfolgreich für die folgende Mail {} angelegt.\n\nViel Spaß',
    _.accoutErrorTryLateOrContant: 'Ihr Account konnte nicht angelegt werden, bitte versuchen Sie später erneut oder kontaktieren Sie uns',
    _.nicknameIs: 'Ihr Benutzername lautet: ',
    _.newPwdIs: 'Ihr Passwort lautet: ',
    _.newPwdInfo: 'Wenn Sie die E-Mail nicht angefordert haben, informieren Sie bitte den Betreiber von D-BAS',
    _.dbasPwdRequest: 'D-BAS Passwort Anfrage',
    _.antispamquestion: 'Was ist',
    _.defaultView: 'Standardansicht',
    _.positions: 'Positionen',
    _.labels: 'Beschriftungen',
    _.showMyPath: 'Meinen Pfad einblenden',
    _.hideMyPath: 'Meinen Pfad ausblenden',
    _.myDiscussions: 'Meine Diskussionen',
    _.myStatements: 'Meine Aussagen',
    _.supportsOnMyStatements: 'Unterstützungen',
    _.attacksOnMyStatements: 'Angriffe',
    _.addATopic: 'Thema hinzufügen',
    _.editIssueViewChangelog: 'Thema editieren / Änderungprotokoll einsehen',
    _.editTitleHere: 'Bitte bearbeiten Sie hier den Title:',
    _.editInfoHere: 'Bitte bearbeiten Sie hier die Info:',
    _.viewChangelog: 'Änderungprotokoll einsehen',
    _.editStatementHere: 'Bitte bearbeiten Sie hier die Aussage:',
    _.editTextMessage: 'Ihr Text wurde geändert von {}\nVon: {}\nZu: {}\nWo: {}',
    _.editTextMessageForHtml: 'Ihr Text wurde geändert von {}<br>Von: {}<br>Zu: {}<br>Wo: <a href="{}">{}</a>',
    _.save: 'Sichern',
    _.cancel: 'Abbrechen',
    _.submit: 'Senden',
    _.close: 'Schließen',
    _.urlSharing: 'URL teilen',
    _.urlSharingDescription: 'Teilen Sie diese URL:',
    _.warning: 'Warnung',
    _.resumeHere: 'Hier weitermachen',
    _.aand: 'und',
    _.andor: 'und/oder',
    _.addStatementRow: 'Weiteres Argument angegeben',
    _.addedEverything: 'Alles wurde hinzugefügt',
    _.addTopic: 'Thema hinzufügen',
    _.at: 'am',
    _.alreadyInserted: 'Dies ist ein Duplikat und schon vorhanden',
    _.addIssueInfo: 'Sie brauchen mindestens {} Punkte um ein neues Thema anzulegen',
    _.addPremisesRadioButtonText: 'Lass\' mich meine eigenen Gründe angeben',
    _.addArgumentsRadioButtonText: 'Lass\' mich meine eigenen Aussagen angeben',
    _.argumentContainerTextIfPremises: 'Sie möchten Ihre eigenen Gründe angeben?',
    _.argumentContainerTextIfArguments: 'Sie möchten Ihre eigenen Argumente angeben?',
    _.addPremiseRadioButtonText: 'Lass\' mich meinen eigenen Grund angeben',
    _.addArgumentRadioButtonText: 'Lass\' mich meine eigene Aussage angeben',
    _.argumentContainerTextIfPremise: 'Sie möchten Ihren eigenen Grund angeben?',
    _.argumentContainerTextIfArgument: 'Sie möchten Ihr eigenes Argument angeben?',
    _.argumentContainerTextIfConclusion: 'Was ist Ihre Idee? Was sollten wir unternehmen?',
    _.argueAgainstPositionToggleButton: 'Oder wenn Sie gegen eine Position argumentieren möchten, drücken Sie bitte diesen Schalter:',
    _.argueForPositionToggleButton: 'Oder wenn Sie für eine Position argumentieren möchten, drücken Sie bitte diesen Schalter:',
    _.argumentFlaggedBecauseOfftopic: 'Dieses Argument wurde von einer/m Benutzer/in gemeldet, da es möglicherweise <strong>nicht themenbezogen</strong> ist',
    _.argumentFlaggedBecauseSpam: 'Dieses Argument wurde von einer/m Benutzer/in gemeldet, da es möglicherweise <strong>Spam</strong> ist',
    _.argumentFlaggedBecauseHarmful: 'Dieses Argument wurde von einer/m Benutzer/in gemeldet, da es möglicherweise <strong>nicht angebracht, schädlich oder missbräuchlich</strong> ist',
    _.argumentFlaggedBecauseOptimization: 'Dieses Argument wurde von einer/m Benutzer/in gemeldet, da es möglicherweise <strong>sprachlicher Korrektur</strong> bedarf',
    _.argumentFlaggedBecauseEdit: 'Dieses Argument wurde von einer/m Benutzer/in sprachlich verbessert',
    _.argumentFlaggedBecauseDuplicate: 'Dieses Argument wurde von einer/m Benutzer/in als Duplikat markiert',
    _.argumentFlaggedBecauseSplit: 'Diese Aussage wurde von einer/m Benutzer/in markiert, da diese getrennt werden soll',
    _.argumentFlaggedBecauseMerge: 'Diese Aussagen wurden von einer/m Benutzer/in markiert, da diese zusammengefügt werden sollen',
    _.argument_optimization_description: 'Das Argument ist richtig, sollte aber sprachlich/grammatikalisch verbessert werden',
    _.argument_offtopic_or_irrelevant_description: 'Die Bedeutung des Arguments ist nicht themenbezogen oder Spam',
    _.argument_statement_harmful_description: 'Bestimmte Personen würden diesen Inhalt nicht passend für eine respektvolle Diskussion halten',
    _.alternatively: 'Alternativ',
    _.argument: 'Argument',
    _.accept: 'für',
    _.assistance: 'Unterstützung',
    _.andIDoNotBelieveCounter: 'und ich glaube, dass ist kein gutes Gegenargument für',
    _.andIDoNotBelieveArgument: 'und ich glaube, dass ist kein gutes Argument für',
    _.andTheyDoNotBelieveCounter: 'und sie glauben, dass ist kein gutes Gegenargument für',
    _.andTheyDoNotBelieveArgument: 'und sie glauben, dass ist kein gutes Argument für',
    _.asReasonFor: 'als einen Grund für',
    _.askAFriend: 'Einen Freund fragen',
    _.attackedBy: 'Sie wurden attackiert mit',
    _.attackedWith: 'Sie haben attackiert mit',
    _.attackPosition: 'Position angreifen',
    _.agreeBecause: 'Ich stimme zu, weil ',
    _.andIDoBelieveCounterFor: 'und ich glaube, dass ist ein gutes Gegenargument für',
    _.andIDoBelieveArgument: 'und ich glaube, dass ist ein gutes Argument für',
    _.addArguments: 'Argumente hizufügen',
    _.addStatements: 'Aussagen hizufügen',
    _.addArgumentsTitle: 'Fügt neue Argumente hinzu',
    _.acceptItTitle: 'Einsenden...',
    _.acceptIt: 'Eintragen...',
    _.agreeToThis0: 'Keiner stimmt der Aussage zu',
    _.agreeToThis1: 'stimmt der Aussage zu',
    _.agreeToThis2: 'stimmen der Aussage zu',
    _.attitudeFor: 'Einstellungen zu',
    _.alreadyFlaggedByOthers: 'Diese Aussage wurde uns schon gemeldet',
    _.alreadyFlaggedByYou: 'Sie haben diese Aussage schon gemeldet',
    _.alreadyEditProposals: 'Wir konnten nicht alle Vorschläge annehmen, da schon Vorschläge gemacht wurden',
    _.alreadyExecuted: 'Da war wohl jemand schneller. Diese Entscheidung ist schon gelaufen',
    _.breadcrumbsStart: 'Start',
    _.breadcrumbsChoose: 'Mehrere Gründe für',
    _.breadcrumbsJustifyStatement: 'Wieso denken Sie das',
    _.breadcrumbsGetPremisesForStatement: 'Prämissen',
    _.breadcrumbsMoreAboutArgument: 'Mehr Über',
    _.breadcrumbsReplyForPremisegroup: 'Antwort für Gruppe',
    _.breadcrumbsReplyForResponseOfConfrontation: 'Begründung von',
    _.breadcrumbsReplyForArgument: 'Antwort fürs Argument',
    _.bugSubmit: 'Fehler senden',
    _.butOtherParticipantsDontHaveOpinionRegardingYourOpinion: 'aber andere Teilnehmer haben keine Meinung bezüglich ihrer Eingabe',
    _.butOtherParticipantsDontHaveArgument: 'aber andere Teilnehmer haben keine Begründung für dafür',
    _.butOtherParticipantsDontHaveCounterArgument: 'aber andere Teilnehmer haben kein Gegenargument',
    _.butIDoNotBelieveCounterFor: 'Aber ich glaube nicht, dass es ein guter Grund dagegen ist, dass {}',
    _.butIDoNotBelieveArgumentFor: 'Aber ich glaube nicht, dass es ein guter Grund dafür ist, dass {}',
    _.butIDoNotBelieveReasonForReject: 'Aber ich glaube nicht, dass das zur Aussage führt',
    _.butTheyDoNotBelieveCounter: 'Aber sie glauben, dass es {}keine gute Begründung dagegen{} ist, {}dass{}',
    _.butTheyDoNotBelieveArgument: 'Aber sie glauben, dass es {}keine gute Begründung dafür{} ist, {}dass{}',
    _.butSheDoesNotBelieveCounter: 'Aber sie glaubt, dass es {}keine gute Begründung dagegen{} ist, {}dass{}',
    _.butSheDoesNotBelieveArgument: 'Aber sie glaubt, dass es {}keine gute Begründung dafür{} ist, {}dass{}',
    _.butHeDoesNotBelieveCounter: 'Aber er glaubt, dass es {}keine gute Begründung dagegen{} ist, {}dass{}',
    _.butHeDoesNotBelieveArgument: 'Aber er glaubt, dass es {}keine gute Begründung dafür{} ist, {}dass{}',
    _.butYouCounteredWithInterest: 'Jedoch haben Sie sich dann dafür interessiert, dass',
    _.butYouCounteredWithArgument: 'Jedoch haben Sie dann das Gegenargument gebracht, dass',
    _.butYouAgreedWith: 'Und Sie haben zugestimmt, weil',
    _.but: 'aber',
    _.butWhich: 'aber welches',
    _.butThisDoesNotRejectArgument: 'Jedoch widerspricht das nicht dem Argument, dass {}',
    _.butThisDoesNotRejectStatement: 'Jedoch widerspricht das nicht der Aussage, dass {}',
    _.clickHereForRegistration: 'Klicken <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">hier</a> für die Anmeldung oder eine Registrierung',
    _.clickForMore: 'Bitte hier klicken',
    _.confirmation: 'Bestätigung',
    _.contactSubmit: 'Nachricht senden',
    _.contact: 'Kontakt',
    _.confirmTranslation: 'Wenn Sie die Sprache ändern, geht Ihr aktueller Fortschritt verloren',
    _.correctionsSet: 'Ihre Korrektur wurde gesetzt',
    _.countOfArguments: 'Anzahl der Argumente',
    _.countOfPosts: 'Anzahl der Beiträge',
    _.checkFirstname: 'Ihre Eingabe ist leer. Bitte überprüfen Sie Ihren Vornamen',
    _.checkLastname: 'Ihre Eingabe ist leer. Bitte überprüfen Sie Ihren Nachnamen',
    _.checkNickname: 'Ihre Eingabe ist leer. Bitte überprüfen Sie Ihren Benutzernamen',
    _.checkLanguage: 'Ihre Eingabe ist leer. Bitte überprüfen Sie Ihren Sprache',
    _.checkEmail: 'Ihre Eingabe ist leer. Bitte überprüfen Sie Ihre E-Mail',
    _.checkPassword: 'Ihre Eingabe ist leer. Bitte überprüfen Sie das Passwort',
    _.checkConfirmation: 'Ihre Eingabe ist leer. Bitte überprüfen Sie die Passwort-Bestätigung',
    _.checkPasswordConfirm: 'Die Kennwörter stimmen nicht überein. Bitte überprüfen Sie Ihre Eingabe',
    _.clickToChoose: 'Klicken zum wählen',
    _.clearStatistics: 'Statistik löschen',
    _.canYouGiveAReason: 'Können Sie einen Grund angeben?',
    _.canYouGiveAReasonFor: 'Können Sie einen Grund für folgendes angeben:',
    _.canYouGiveACounterArgumentWhy1: 'Können Sie begründen, wieso sie gegen',
    _.canYouGiveACounterArgumentWhy2: 'sind?',
    _.canYouGiveACounter: 'Können Sie einen Grund dagegen angeben?',
    _.canYouGiveAReasonForThat: 'Können Sie dafür einen Grund angeben?',
    _.canYouBeMorePrecise: 'Können Sie bitte noch genauer sein? Was finden Sie an der Behauptung falsch?',
    _.completeView: 'Komplette View',
    _.completeViewTitle: 'Kompletten Graphen anzeigen',
    _.conclusionIsMissing: 'Conclusion ID fehlt',
    _.currentDiscussion: 'Die aktuelle Diskussion hat folgendes Thema',
    _.congratulation: 'Glückwunsch',
    _.docs: 'Dokumentation',
    _.dialogView: 'Dialog-Ansicht',
    _.dialogViewTitle: 'Dialog-Ansicht',
    _.dateString: 'Datum',
    _.disagreeBecause: 'Ich widerspreche, weil ',
    _.description_undermine: 'Diese Aussage ist gegen die Prämisse',
    _.description_support: 'Diese Aussage ist für die Prämisse',
    _.description_undercut: 'Diese Aussage ist gegen die Begründung (undercut). Sie glauben nicht, dass aus der Prämisse die Konklusion folgt',
    _.description_rebut: 'Diese Aussage ist gegen die Konklusion',
    _.description_no_opinion: 'Sie haben keine Meinung oder möchten diesen Punkt nur überspringen',
    _.decisionIndex7: 'Klicks in der Diskussion - Letzte 7 Tage',
    _.decisionIndex30: 'Klicks in der Diskussion - Letzte 30 Tage',
    _.decisionIndex7Info: 'Anzahl an getroffenen Entscheidungen (bedingt durch Klicks im System), in den letzten 7 Tage',
    _.decisionIndex30Info: 'Anzahl an getroffenen Entscheidungen (bedingt durch Klicks im System), in den letzten 30 Tage',
    _.dataRemoved: 'Daten wurden erfolgreich gelöscht',
    _.didYouMean: 'Top 10 der Aussagen, die Sie eventuell meinten:',
    _.discussionEnd: 'Die Diskussion endet hier',
    _.discussionStart: 'Diskussionsübersicht',
    _.discussionEndAndReadOnly: 'Die Diskussion endet hier. Da diese nur noch lesbar ist, kann keine weitere Aussage mehr hinzugefügt werden',
    _.discussionCongratulationEnd: 'Die Diskussion endet hier, da weitere Teilnehmer aktuell kein Gegenargument mehr haben',
    _.discussionEndLinkTextRestartDiscussion: 'Sie können den Button unten nutzen, um die Diskussion zu neu zu starten',
    _.discussionEndLinkTextWithQueueLoggedIn: 'Suchen Sie nach weiteren Aufgaben? Schauen Sie doch einmal in unsere <a id="discussionEndReview">Prüfsektion</a>. Alternativ können Sie den Button unten nutzen um die Diskussion neu zu starten',
    _.discussionEndLinkTextWithQueueNotLoggedIn: 'Suchen Sie nach weiteren Aufgaben? <a  data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">Login</a> und schauen Sie doch einmal in unsere <a id="discussionEndReview">Prüfsektion</a>. Alternativ können Sie den Button unten links nutzen um die Diskussion zu wiederholen',
    _.duplicateDialog: 'Diese Textversion wurde schon editiert und ist somit veraltet.\nMöchten Sie diese Version dennoch als die aktuellste markieren?',
    _.duplicate: 'Duplikat in',
    _.displayControlDialogGuidedTitle: 'Dialog-Ansicht',
    _.displayControlDialogGuidedBody: 'Sie werden nie etwas wie eine Argumentationskarte sehen, da das System Sie führt. Somit ist das System dynamisch und generisch für Sie',
    _.displayControlDialogIslandTitle: 'Insel-Ansicht',
    _.displayControlDialogIslandBody: 'Okay, Sie möchten mehr sehen, aber nicht alles? Genau dafür haben wie eine Insel-Ansicht als weitere Modus. Mit dieser Möglichkeit sehen Sie alle Aussagen, die mit Ihrem aktuellen Standpunkt verbunden sind',
    _.displayControlDialogExpertTitle: 'Experten-Ansicht',
    _.displayControlDialogExpertBody: 'Sie sind ein Experte? In Ordnung, dann dürfen Sie alles auf einen Blick sehen',
    _.displayControlDialogGraphTitle: 'Graph-Ansicht',
    _.displayControlDialogGraphBody: 'Darstellung der Diskussion als Graph',
    _.discussionInfoTooltipSg: 'Die Diskussion wurde am {} um {} Uhr gestartet und hat nur {} Argument. Kommen\' und machen Sie mit',
    _.discussionInfoTooltipPl: 'Die Diskussion wurde am {} um {} Uhr gestartet und hat schon {} Argumente',
    _.discussionIsReadOnly: 'Die Diskussion kann nur gelesen werden',
    _.disagreeToThis0: 'keiner widerspricht der Aussage',
    _.disagreeToThis1: 'widerspricht der Aussage',
    _.disagreeToThis2: 'widersprechen der Aussage',
    _.doesNotHold: 'keine gute Idee ist',
    _.isNotRight: 'nicht richtig ist',
    _.isNoGoodJustification: 'keine gute Begründung ist',
    _.issueEnableDescription: 'Zeigt an, ob das Thema allgemein verfügbar ist',
    _.issuePublicDescription: 'Zeigt an, ob das Thema für jede/n Nutzer/in verfügbar ist oder erst nach Einladung via Link (privat)',
    _.issueWritableDescription: 'Zeigt an, ob das Scheiben von Beiträgen für diese Diskussion erlaubt ist',
    _.doesJustify: 'gerechtfertigen, dass',
    _.doesNotJustify: 'nicht gerechtfertigen, dass',
    _.deleteTrack: 'Track löschen',
    _.deleteStatement: 'Aussage löschen',
    _.disassociateStatement: 'Vom Statement distanzieren',
    _.delete: 'Löschen',
    _.deleteHistory: 'History löschen',
    _.doYouWantToEnterYourStatements: 'Möchten Sie Ihre eigenen Gründe angeben?',
    _.doNotHesitateToContact: 'Zögern Sie nicht, uns zu <span style="cursor: pointer;" id="contact-on-error"><strong>kontaktieren (hier klicken)</strong></span>',
    _.dataNowLocked: 'Sie können die Daten nun bearbeiten',
    _.dataUnlocked: 'Daten wurden freigegeben',
    _.dataAlreadyLockedByYou: 'Sie bearbeiten schon einen Datensatz. Schließen Sie diese Bearbeitung bitte zuerst ab',
    _.dataAlreadyLockedByOthers: 'Dieser Datensatz wird gerade durch andere Teilnehmer bearbeitet',
    _.earlierYouArguedThat: 'Zuerst haben Sie argumentiert, dass',
    _.eachStatement: 'pro Aussage',
    _.editIndex: 'Anzahl an Änderungen - Letzte 30 Tage',
    _.editIndexInfo: 'Anzahl an Änderungen',
    _.euCookiePopupTitle: 'Diese Seite nutzt Cookies und Matomo',
    _.euCookiePopupText: 'Wir benutzen Sie, um Ihnen die beste Erfahrung zu ermöglichen. Wenn Sie unsere Seite weiter nutzen möchten, akzeptieren Sie bitte die Cookies. Zusätzlich tracken wir Ihre Aktionen und speichern diese anonym ab. Dabei wird Ihre IP-Adresse maskiert',
    _.euCookiePopoupButton1: 'Weiter',
    _.euCookiePopoupButton2: 'Lerne&nbsp;mehr',
    _.empty_news_input: 'Nachrichten-Titel oder Text ist leer oder zu kurz',
    _.empty_notification_input: 'Nachrichten-Titel oder Text ist leer oder zu kurz',
    _.email: 'E-Mail',
    _.emailWasSent: 'E-Mail wurde gesendet.',
    _.emailWasNotSent: 'E-Mail wurde nicht gesendet',
    _.emailUnknown: 'Die Adresse ist nicht gültig',
    _.emailSentGeneric: 'Falls die Mailadresse gefunden werden konnte, schicken wir Ihnen eine Mail mit Instruktionen zu',
    _.emailBodyText: 'Dies ist eine automatisch generierte E-Mail von D-BAS {}.\nBei Rückfragen können Sie gerne eine E-Mail an dbas@cs.uni-duesseldorf.de verfassen.\nDieses System ist Teil einer Doktorarbeit',
    _.emailArgumentAddTitle: 'D-BAS Infos zum Argument',
    _.emailArgumentAddBody: 'Zu Ihrem Argument wurden weitere Informationen hinzugefügt. Schauen Sie doch mal rein:',
    _.edit: 'Bearbeiten',
    _.error_code: 'Fehler-Code',
    _.editTitle: 'Aussage bearbeiten',
    _.editAlreadyTitle: 'Diese Aussage wurde schon bearbeiten und wird nun durch die Community begutachtet',
    _.exampleName: 'Heinrich Heine',
    _.exampleMail: 'heinrich.heine@hhu.de',
    _.examplePhone: '+49 (0)211 81-123456',
    _.exampleMessage: 'Sehr gute Arbeit!',
    _.exampleMessageBug: 'Auf der Seite https://dbas.cs.uni-duesseldorf.de/discuss/a/b verhält sich D-BAS komisch, weil ...',
    _.exampleNickname: 'Democrator',
    _.exampleNicknameLdap: 'hehei001',
    _.examplePassword: '********',
    _.exampleFirstname: 'Heinrich',
    _.exampleLastname: 'Heine',
    _.exampleStatement: 'Bitte fügen Sie hier Ihr Zitat (von der Webseite) ein',
    _.exampleSource: 'Bitte fügen Sie hier Ihre Quelle (URL der Webseite) ein',
    _.exampleSearchDuplicate: 'Hier können Sie suchen',
    _.examplePosition: 'wir etwas unternehmen sollten',
    _.exampleReason: 'das ein Grund dafür ist',
    _.exampleAddTopicTitle: 'z.B.: Hund oder Katze',
    _.exampleAddTopicQuestion: 'z.B.: Ihre Familie diskutiert über Hunde und Katzen. Was ist Ihre Meinung?',
    _.exampleAddTopicDescription: 'z.B.: In den letzten Tagen diskutiert Ihre Famile über den neuen Zuwachs bei den Haustieren. Zur Auswahl stehen nun Hunde und Katzen. Nun zählt Ihre Meinung',
    _.everythingSaved: 'Alles gespeichert',
    _.opinionSaved: 'Ihre Meinung wurde gespeichert',
    _.feelFreeToLogin: 'Wenn Sie fortfahren möchten, <u><a data-href="login" data-toggle="modal" data-target="#popup-login" title="Anmelden">melden</a></u> Sie sich bitte an',
    _.forText: 'für',
    _.forThat: 'dafür, dass',
    _.fillLine: 'Bitte, füllen Sie diese Zeilen mit Ihrer Meldung',
    _.firstConclusionRadioButtonText: 'Lass mich meine eigenen Ideen einfügen',
    _.firstArgumentRadioButtonText: 'Lass mich meine eigenen Aussagen einfügen',
    _.feelFreeToShareUrl: 'Bitte teilen Sie diese URL',
    _.fetchLongUrl: 'Normale URL',
    _.fetchShortUrl: 'Kurze URL',
    _.forgotPassword: 'Passwort vergessen',
    _.firstOneInformationText: 'Sie sind der/die Erste, der Informationen über "{}" haben möchte',
    _.firstOneInformationTextM: 'Sie sind der Erste, der Informationen über "{}" haben möchte',
    _.firstOneInformationTextF: 'Sie sind die Erste, der Informationen über "{}" haben möchte',
    _.firstOneReason: 'Sie sind der/die Erste mit diesem Argument. Bitte geben Sie Ihre Begründung an',
    _.firstOneReasonM: 'Sie sind der Erste mit dieser Aussage. Bitte geben Sie Ihre Begründung an',
    _.firstOneReasonF: 'Sie sind die Erste mit dieser Aussage. Bitte geben Sie Ihre Begründung an',
    _.firstPositionTextM: 'Sie sind der Erste in dieser Diskussion',
    _.firstPositionTextF: 'Sie sind die Erste in dieser Diskussion',
    _.firstPositionText: 'Sie sind der/die Erste in dieser Diskussion',
    _.firstPremiseText1M: 'Sie sind der Erste, der sagt, dass {}',
    _.firstPremiseText1F: 'Sie sind die Erste, der sagt, dass {}',
    _.firstPremiseText1: 'Sie sind der/die Erste, der sagt, dass ',
    _.firstPremiseText2: 'Bitte begründen Sie Ihre Aussage.',
    _.firstname: 'Vorname',
    _.fromm: 'von',
    _.finish: 'Ende',
    _.finishTitle: 'Diskussion beenden',
    _.fieldtest: 'Feldtest',
    _.hold: 'stimmen',
    _.gender: 'Geschlecht',
    _.goBack: 'Klicken, um zurückzugehen',
    _.goHome: 'Startseite',
    _.goStepBack: 'Einen Schritt zurück',
    _.generateSecurePassword: 'Sicheres Passwort erstellen',
    _.goodPointTakeMeBackButtonText: 'Ich stimme zu, dass ist ein gutes Argument. Geh einen Schritt zurück',
    _.group_uid: 'Gruppe',
    _.goBackToTheDiscussion: 'Geh zur Diskussion',
    _.goForward: 'Klicken, um weiterzugehen',
    _.goodPointAndUserIsInterestedTooM: '{}Das ist ein guter Punkt und{} {} {}interessiert sich auch für dieselbe Behauptung. Er sagt:{} {}',
    _.goodPointAndUserIsInterestedTooF: '{}Das ist ein guter Punkt und{} {} {}interessiert sich auch für dieselbe Behauptung. Sie sagt:{} {}',
    _.goodPointAndOtherParticipantsIsInterestedToo: '{}Das ist ein guter Punkt und weitere Teilnehmer sind ebenfalls in Ihrer Behauptung interessiert. Sie sagen:{} {}',
    _.haveALookAt: 'Schauen Sie sich folgendes einmal an: ',
    _.hidePasswordRequest: 'Verstecke die Passwort-Anfrage',
    _.hideGenerator: 'Verstecke Generator',
    _.history: 'Geschichte',
    _.howeverIHaveMuchStrongerArgumentRejectingThat: 'Jedoch habe ich ein viel stärkeres Argument dagegen, dass',
    _.howeverIHaveMuchStrongerArgumentAcceptingThat: 'Jedoch habe ich ein viel stärkeres Argument dafür, dass',
    _.howeverIHaveMuchStrongerArgumentTo: 'Jedoch habe ich ein viel stärkeres Argument',
    _.howeverIHaveMuchStrongerArgument: 'Jedoch habe ich ein viel stärkeres Argument',
    _.howeverIHaveEvenStrongerArgumentRejecting: 'Jedoch habe ich ein stärkeres Argument gegen:',
    _.howeverIHaveEvenStrongerArgumentAccepting: 'Jedoch habe ich ein stärkeres Argument für:',
    _.imprint: 'Impressum',
    _.internalFailureWhileDeletingTrack: 'Interner Fehler, bitte versuchen Sie es später erneut',
    _.internalFailureWhileDeletingHistory: 'Interner Fehler, bitte versuchen Sie es später erneut',
    _.internalError: '<strong>Interner Fehler:</strong> Wahrscheinlich ist der Server nicht erreichbar. Bitte laden Sie die Seite erneut',
    _.internalErrorHTTPS: 'Interner Fehler beim Login',
    _.internalKeyError: 'Interner Fehler beim Verarbeiten von Daten',
    _.inputEmpty: 'Ihre Eingabe ist leer',
    _.informationForExperts: 'Infos für Experten',
    _.invalidTableName: 'Ungültiger Tabellenname',
    _.issueList: 'Themen',
    _.issueNotFound: 'Es konnte kein Diskussionsthema gefunden werden',
    _.irrelevant: 'Irrelevant',
    _.itIsTrueThat: 'ich akzeptiere, dass',
    _.maybeItIsTrueThat: 'Vielleicht stimmt es, dass',
    _.itIsTrueThatAnonymous: 'Es ist richtig, dass',
    _.itIsTrue1: 'ich akzeptiere',
    _.itIsTrue2: '',
    _.itIsFalseThat: 'ich lehne ab, dass',
    _.itIsFalseThatAnonymous: 'Es ist falsch, dass',
    _.itIsFalse1: 'ich lehne',
    _.itIsFalse2: 'ab',
    _.itTrueIsThat: 'es richtig ist, dass',
    _.itFalseIsThat: 'es falsch ist, dass',
    _.isFalse: 'ist falsch',
    _.isTrue: 'richtig ist',
    _.areTrue: 'sind richtig',
    _.isNotAGoodIdea: 'falsch ist',
    _.isNotAGoodReasonFor: 'ist kein guter Grund für',
    _.isNotAGoodReasonAgainstArgument: 'ist kein guter Grund gegen das Argument, dass ',
    _.itIsNotRight: 'es nicht richtig ist, dass',
    _.isNotAGoodIdeaInColor: '<span class=\'text-danger\'>falsch ist</span>',
    _.initialPositionInterest: 'Ich möchte darüber reden, dass',
    _.invalidEmail: 'Ihre E-Mail ist ungültig',
    _.iAcceptCounter: 'und ich akzeptiere, dass es ein Argument gegen',
    _.iAcceptArgument: 'und ich akzeptiere, dass es ein Argument für',
    _.iAcceptCounterThat: 'und ich akzeptiere, dass es ein Argument dagegen ist, dass',
    _.iAcceptArgumentThat: 'und ich akzeptiere, dass es ein Argument dafür ist, dass',
    _.iAgreeWith: 'Ich find das richtig',
    _.iAgreeWithInColor: 'Ich finde das <span class=\'text-success\'>richtig</span>',
    _.iDisagreeWith: 'Ich finde das falsch',
    _.iDisagreeWithInColor: 'Ich finde das <span class=\'text-danger\'>falsch</span>',
    _.iDoNotKnow: 'Ich weiß es nicht, dass',
    _.iDoNotKnowInColor: 'Ich <span class=\'text-info\'>weiß es nicht</span>',
    _.iHaveNoOpinionYet: 'Ich weiß es nicht, dass',
    _.iHaveNoOpinion: 'Ich weiß es nicht',
    _.iHaveNoOpinionYetInColor: 'Ich <span class=\'text-info\'>weiß es nicht</span>. Zeige mir eine Begründung zu dieser Aussage',
    _.iHaveMuchStrongerArgumentRejecting: 'Ich habe ein viel stärkeres Argument zum Ablehnen von',
    _.iHaveEvenStrongerArgumentRejecting: 'Ich habe ein stärkeres Argument zum Ablehnen von',
    _.iHaveMuchStrongerArgumentAccepting: 'Ich habe ein viel stärkeres Argument zum Akzeptieren von',
    _.iHaveEvenStrongerArgumentAccepting: 'Ich habe ein stärkeres Argument zum Akzeptieren von',
    _.iNoOpinion: 'Ich habe keine Meinung bezüglich',
    _.interestingOnDBAS: 'Interessante Diskussion in D-BAS',
    _.informationForStatements: 'Informationen zu den Aussagen',
    _.relativePopularityOfStatements: 'Relative Beliebheit der Aussagen',
    _.requestPassword: 'Passwort anfordern',
    _.jumpAnswer0: 'Ja, ich halte die {} für richtig und finde die {} gut',
    _.jumpAnswer1: 'Ja, ich halte die {} für richtig, aber ich möchte meine eigene {} angeben',
    _.jumpAnswer2: 'Ja, ich halte die {} für richtig, aber sie wird nicht von der {} unterstützt',
    _.jumpAnswer3: 'Nein, ich halte die {} für falsch',
    _.jumpAnswer4: 'Nein, ich finde die {} nicht gut',
    _.supportAnswer0: 'Ich finde die {} gut',
    _.supportAnswer1: 'Ich möchte eine neue {} angeben',
    _.supportAnswer2: 'Die {} ist kein Grund für die {}',
    _.supportAnswer3: 'Ich finde die {} nicht gut',
    _.justLookDontTouch: 'Nur anschauen, nichts anfassen',
    _.keyword: 'Schlüsselwort',
    _.keywordStart: 'Start',
    _.keywordChooseActionForStatement: 'Einstellung zu',
    _.keywordGetPremisesForStatement: 'Prämissen von',
    _.keywordMoreAboutArgument: 'Mehr über',
    _.keywordReplyForPremisegroup: 'Antwort auf das Argument',
    _.keywordReplyForResponseOfConfrontation: 'Begründung von',
    _.keywordReplyForArgument: 'Konfrontation',
    _.keepSetting: 'Entscheidung merken',
    _.holds: 'ist richtig',
    _.holdsInColor: 'ist <span class=\'text-success\'>richtig</span>',
    _.hideAllUsers: 'Verstecke alle Benutzer',
    _.hideAllAttacks: 'Verstecke alle Angriffe',
    _.letMeExplain: 'Lass\' es mich so erklären',
    _.levenshteinDistance: 'Levenshtein-Distanz',
    _.languageCouldNotBeSwitched: 'Leider konnte die Sprache nicht gewechselt werden',
    _.last_action: 'Letzte Aktion',
    _.last_login: 'Letzte Anmeldung',
    _.login: 'Login',
    _.logfile: 'Logdatei für',
    _.letsGo: 'Klicken Sie hier um direkt zu starten',
    _.letsGoBack: 'Zurück',
    _.letsGoHome: 'Ab zur Startseite',
    _.langNotFound: 'Sprache nicht gefunden',
    _.latestNewsFromDiscussion: 'Die aktuellen Neuigkeiten aus der Diskussion über',
    _.latestNewsFromDBAS: 'Die aktuellen Neugkeitenen von D-BAS, einem Dialog-Basierten Argumentationssystem',
    _.ldapInfo: 'Wir benutzen das Personenverzeichnis der Uni Düsseldorf. Alle Daten werden SSL-verschlüsselt gesendet und unter keinen Umständen an Dritte weitergegeben',
    _.more: 'Mehr',
    _.medium: 'mittel',
    _.minLength: 'Mindestlänge',
    _.myArgument: 'mein Argument',
    _.mark_as_opinion: 'Klicken Sie, um dies als Ihre Meinung zu markieren',
    _.unmark_as_opinion: 'Klicken Sie, um von dieser Meinung abzurücken',
    _.user_is_admin: 'Ihr Diskussionsgener ist ein Administrator',
    _.user_is_special: 'Ihr Diskussionsgener ist etwas Besonderes',
    _.user_is_author: 'Ihr Diskussionsgener ist ein Nachrichtenauthor',
    _.newNotification: 'Sie haben eine neue Benachrichtigung',
    _.newMention: 'Sie wurden in einem Beitrag erwähnt',
    _.newPremiseRadioButtonText: 'Nichts von all dem. Ich möchte einen neuen Grund angeben',
    _.newPremiseRadioButtonTextAsFirstOne: 'Ja, ich möchte einen neuen Grund angeben',
    _.newConclusionRadioButtonText: 'Nichts von all dem. Ich habe eine andere Idee',
    _.newConclusionRadioButtonTextNewIdea: 'Ich habe eine neue Idee',
    _.newIssueErrorMsg: 'Es fehlt',
    _.newIssueTitle: 'Titel',
    _.newIssueInfo: 'Leitfrage',
    _.newIssueLongInfo: 'detaillierte Informationen',
    _.newsAboutDbas: 'Nachrichten über D-BAS',
    _.next: 'Nächster Eintrag',
    _.nickname: 'Benutzername',
    _.noOtherAttack: 'Das System hat kein anderes Gegenargument',
    _.noCorrections: 'Keine gültige Korrektur für die Aussage',
    _.noDecisionDone: 'Es liegt keine Entscheidung vor',
    _.noCorrectionsSet: 'Korrektur wurde nicht gespeichert, da der Benutzer unbekannt ist. Sind Sie angemeldet?',
    _.notInsertedErrorBecauseEmpty: 'Ihre Idee wurde nicht gespeichert, da das Feld leer oder der Inhalt zu kurz ist',
    _.notInsertedErrorBecauseDuplicate: 'Ihre Idee wurde nicht gespeichert, da Ihre Idee ein Duplikat ist',
    _.notInsertedErrorBecauseUnknown: 'Ihre Idee wurde aufgrund eines unbekannten Fehlers nicht gespeichert',
    _.notInsertedErrorBecauseInternal: 'Ihre Idee wurde aufgrund eines internen Fehlers nicht gespeichert',
    _.noEntries: 'Keine Einträge vorhanden',
    _.noTrackedData: 'Keine Daten wurden gespeichert',
    _.noDataSelected: 'Nichts ausgewählt',
    _.number: 'Nr',
    _.note: 'Hinweis',
    _.now: 'Jetzt',
    _.nowYouSayThat: 'Nun sagen Sie, dass',
    _.no_entry: 'Kein Eintrag',
    _.no_arguments: 'Keine Argumente für diese Meinung',
    _.noRights: 'Sie haben nicht genügend Rechte',
    _.notLoggedIn: 'Sie sind nicht angemeldet',
    _.on: 'An',
    _.off: 'Aus',
    _.of: 'von',
    _.opinion_his: 'ihre Meinung',
    _.opinion_her: 'seine Meinung',
    _.opinion: 'die Meinung',
    _.onlyOneItem: 'Um eine neue Aussage hinzuzufügen, melden Sie sich bitte hier an',
    _.onlyOneItemWithLink: 'Um eine neue Aussage hinzuzufügen, melden Sie sich bitte <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">hier</a> an',
    _.unfortunatelyOnlyOneItem: 'Leider gibt es nur eine Auswahl. Sofern Sie eine neue Aussage hinzufügen möchten, klicken Sie bitte <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">hier</a> um sich anzumelden',
    _.otherParticipantsConvincedYouThat: 'Andere Teilnehmer haben Sie überzeugt, dass',
    _.otherParticipantsThinkThat: 'Andere Teilnehmer denken, dass',
    _.otherParticipantsAgreeThat: 'Andere Teilnehmer stimmen zu, dass',
    _.otherParticipants: 'Andere Teilnehmer',
    _.thinkThat: 'denkst, dass',
    _.agreeThat: 'stimmst zu, dass',
    _.thinksThat: 'denkt, dass',
    _.agreesThat: 'stimmt zu, dass',
    _.that: 'dass',
    _.earlierYouHadNoOpinitionForThisStatement: 'früher hatten Sie keine Meinung dazu, dass {}',
    _.whichConfirmedYourView: 'was {}dein Argument{} stützt',
    _.otherUserDoesntHaveOpinionForThisStatement: 'hat bisher keine Meinung dazu, dass {}',
    _.otherParticipantsDontHaveOpinionForThisStatement: 'Andere Teilnehmer haben bisher keine Meinung dazu',
    _.otherParticipantsDontHaveOpinion: 'Andere Teilnehmer haben bisher keine Meinung dazu, dass',
    _.otherParticipantsDontHaveOpinionRegaringYourSelection: 'Andere Teilnehmer haben bisher keine Meinung zu Ihrer Aussage',
    _.otherParticipantsDontHaveCounter: 'Andere Teilnehmer haben kein Gegenargument für ',
    _.otherParticipantsDontHaveCounterForThat: 'Andere Teilnehmer haben kein Gegenargument dafür',
    _.otherParticipantsDontHaveNewCounterForThat: 'Andere Teilnehmer haben kein neues Gegenargument dafür. Sie habe schon alle Gegenargumente gesehen',
    _.otherParticipantsDontHaveArgument: 'Andere Teilnehmer haben kein Argument für ',
    _.otherParticipantsAcceptBut: 'Andere Teilnehmer akzeptieren Ihr Argument, aber',
    _.otherParticipantDisagreeThat: 'Andere Teilnehmer widersprechen, dass ',
    _.otherUsersClaimStrongerArgumentS: 'hat eine stärkere Aussage zur {} davon, dass',
    _.otherUsersClaimStrongerArgumentP: 'Andere Teilnehmer haben eine stärkere Aussage zur {} davon, dass',
    _.claimsStrongerArgumentRejecting: 'hat eine stärkere Aussage zur Ablehnung davon, dass',
    _.claimsStrongerArgumentAccepting: 'hat eine stärkere Aussage zur Annahme davon, dass',
    _.otherUsersHaveCounterArgument: 'Andere Teilnehmer haben das Gegenargument, dass',
    _.otherUsersSaidThat: 'Andere Teilnehmer haben gesagt, dass',
    _.thenOtherUsersSaidThat: 'Dann haben andere Teilnehmer noch gesagt, dass',
    _.opinionBarometer: 'Stimmungsbarometer',
    _.pleaseAddYourSuggestion: 'Bitte geben Sie Ihren Vorschlag an',
    _.pleaseTryAgainLaterOrContactUs: 'Bitte versuchen Sie es später noch einmal',
    _.previous: 'Vorheriger Eintrag',
    _.premiseGroup: 'Gruppe von Voraussetzung(en)',
    _.premisegroupPopupWarning: 'Achtung: Dieser Schritt kann nicht rückgängig gemacht werden',
    _.publicNickTitle: '(De-)Aktiviert Ihren richtigen Benutzernamen auf Ihrer öffentlichen Seite',
    _.passwordSubmit: 'Passwort ändern',
    _.preferredLangTitle: 'Bevorzugte Sprache für alle Nachrichten/E-Mails',
    _.priv_access_optimization_queue: 'Zugriff auf die Liste für Optimierungen',
    _.priv_access_delete_queue: 'Zugriff auf die Liste für Löschanträge',
    _.priv_access_duplicate_queue: 'Zugriff auf die Liste für Duplikate',
    _.priv_access_edit_queue: 'Zugriff auf die Liste für Änderungen',
    _.priv_access_split_queue: 'Zugriff auf die Liste für geteilte Aussagen',
    _.priv_access_merge_queue: 'Zugriff auf die Zusammenführungs-Queue',
    _.priv_access_history_queue: 'Zugriff auf alle vergangenen Entscheidungen',
    _.priv_access_ongoing_queue: 'Zugriff auf alle aktuell laufenden Entscheidungen',
    _.privacy_policy: 'Datenschutzerklärung',
    _.premiseAndConclusionAreEqual: 'Begründung und Behauptung dürfen nicht identisch sein',
    _.publications: 'Veröffentlichungen',
    _.queueDelete: 'Löschen',
    _.queueOptimization: 'Optimieren',
    _.queueEdit: 'Editieren',
    _.queueDuplicate: 'Duplikate',
    _.queueHistory: 'History',
    _.queueOngoing: 'Aktuell',
    _.queueSplit: 'Teilen',
    _.queueMerge: 'Zusammenführen',
    _.myPosition: 'meinen Standpunkt',
    _.myPositionGenitiv: 'meinem Standpunkt',
    _.the_der: 'der',
    _.the_die: 'die',
    _.the_das: 'das',
    _.report: 'Melden',
    _.review: 'Prüfung',
    _.review_history: 'Frühere Entscheidungen',
    _.review_ongoing: 'Aktuelle Entscheidungen',
    _.reputation: 'Reputation',
    _.reason: 'Begründung',
    _.reportStatement: 'Aussage melden',
    _.reportArgument: 'Argument melden',
    _.reportIssue: 'Fehler melden',
    _.remStatementRow: 'Entfernt diese Reihe.',
    _.registered: 'Registriert',
    _.right: 'Ja',
    _.reject: 'gegen',
    _.rejection: 'Ablehnung',
    _.requestTrack: 'Track anfragen',
    _.refreshTrack: 'Track neuladen',
    _.requestHistory: 'History anfragen',
    _.refreshHistory: 'History neuladen',
    _.requestFailed: 'Anfrage fehlgeschlagen',
    _.restartDiscussion: 'Diskussion neustarten',
    _.restartDiscussionTitle: 'Diskussion neustarten',
    _.restartOnError: 'Bitte laden Sie die Seite erneut oder starten Sie die Diskussion neu, sofern der Fehler bleibt',
    _.recipient: 'Empfänger',
    _.recipientNotFound: 'Empfänger konnte nicht gefunden werden',
    _.reaction: 'Reaktionen',
    _.reactionFor: 'Reaktionen zu',
    _.attitudesOfOpinions: 'Meinungsverhalten',
    _.attackStatement: 'Aussage angreifen',
    _.agreeVsDisagree: 'Zustimmung vs. Ablehnung bei der Aussage, dass',
    _.reference: 'Referenz',
    _.rep_reason_first_argument_click: 'Sie haben Ihr erstes Argument ausgewählt',
    _.rep_reason_first_confrontation: 'Sie haben Ihre erste Konfrontation überstanden',
    _.rep_reason_first_position: 'Sie haben zum ersten Mal eine Positi1on eingegeben',
    _.rep_reason_first_justification: 'Sie haben zum ersten Mal eine Begründung eingegeben',
    _.rep_reason_first_new_argument: 'Sie haben zum ersten Mal ein Argument eingegeben',
    _.rep_reason_new_statement: 'Für jedes weitere Argument, dass Sie eingegeben',
    _.rep_reason_success_flag: 'Sie haben ein Argument erfolgreich markiert',
    _.rep_reason_success_edit: 'Sie haben eine Editierung erfolgreich vorgenommen',
    _.rep_reason_success_duplicate: 'Sie haben ein Duplikat erfolgreich gemeldet',
    _.rep_reason_bad_flag: 'Sie haben die Melde-Funktion missbraucht',
    _.rep_reason_bad_edit: 'Sie haben einen schlechten Editierungsvorschlag gemacht',
    _.rep_reason_bad_duplicate: 'Sie haben ein Duplikat gemeldet, obwohl es keines ist',

    _.reaction_text_undermine: 'Ich halte {} für falsch und möchte widersprechen',
    _.reaction_text_support: 'Ich halte {} für richtig und finde sie überzeugend',
    _.reaction_text_undercut: 'Ich halte {} für richtig, aber sie stützt nicht {}',
    _.reaction_text_undercut_for_dont_know: 'Ich halte {} für richtig, aber sie wird nicht von der {} gestützt',
    _.reaction_text_rebut: 'Ich halte {} für richtig und sie stützt auch {}, aber ich möchte {} trotzdem verteidigen',
    _.reaction_text_rebut_for_dont_know: 'Ich halte {} für falsch und möchte widersprechen',

    _.questionTitle: 'Erhalten Sie mehr Informationen über die Aussage',
    _.saveMyStatement: 'Aussage speichern',
    _.selectStatement: 'Bitte Wählen Sie eine Aussage',
    _.selectMultipleStatementsWhichFlag: 'Sie haben eine Verknüpfung von mehreren Aussagen gewählt. Welche möchten Sie melden?',
    _.showAllUsers: 'Zeig\' alle Benutzer',
    _.showAllArguments: 'Zeig\' alle Argumente',
    _.showAllArgumentsTitle: 'Zeigt alle Argumente',
    _.showAllUsersTitle: 'Zeige alle Nutzer',
    _.strength: 'Stärke',
    _.strong: 'stark',

    _.strongerStatementF: 'Aber sie nennt einen {}Grund {}, dass{}',
    _.strongerStatementM: 'Aber er nennt einen {}Grund {}, dass{}',
    _.strongerStatementP: 'Aber sie nennen einen {}Grund {}, dass{}',
    _.strongerStatementY: 'Aber Sie hatten einen {}Grund {}, dass{}',
    _.accepting: 'dafür',
    _.rejecting: 'dagegen',
    _.strongerStatementEnd: 'davon, dass',

    _.search: 'Suche',
    _.searchForStatements: 'Aussagensuche',
    _.serviceNotAvailable: 'Dienst aktuell nicht verfügbar',
    _.someoneArgued: 'Es wurde gesagt, dass',
    _.soYouEnteredMultipleReasons: 'Sie haben mehrere Gründe eingegeben',
    _.soYourOpinionIsThat: 'Ihre Meinung ist, dass',
    _.soYouWantToArgueAgainst: 'Sie möchten ein Gegenargument bringen für',
    _.shortenedBy: 'welche gekürzt wurde mit',
    _.shareUrl: 'Link teilen',
    _.senderReceiverSame: 'Sender und Empfänger sind gleich',
    _.showMeAnotherArgument: 'Zeige mir ein anderes Argument',
    _.switchDiscussion: 'Diskussionsthema ändern',
    _.switchDiscussionTitle: 'Diskussionsthema ändern',
    _.switchDiscussionText1: 'Wenn Sie akzeptieren, wird das Diskussionsthema gewechselt zu',
    _.switchDiscussionText2: 'und die Diskussion neugestartet',
    _.switchLanguage: 'Sprache ändern',
    _.supportPosition: 'Position unterstützen',
    _.supportsNot: 'unterstützt nicht',
    _.isupport: 'ich halte',
    _.settings: 'Einstellungen',
    _.seperated: 'getrennte',
    _.statement: 'Aussage',
    _.statementIsAbout: 'Die Aussage ist, dass',
    _.statementAbout: 'Die Aussage, dass',
    _.statementAdded: 'Aussage wurde hinzugefügt',
    _.statementIsDuplicate: 'Aussage ist ein Duplikat',
    _.statementsShowAll: 'Alle Antworten anzeigen',
    _.statementsHideAll: 'Antworten ausblenden',
    _.statement_offtopic_or_irrelevant_description: 'Die Beudeutung der Aussage ist nicht themenbezogen oder Spam',
    _.statement_duplicate_description: 'Diese Aussage ist schon leicht verändert im System vorhanden',
    _.statement_merge_description: 'Diese Aussage hängt von einer weiteren Aussage ab und diese sollten verbunden werden',
    _.statement_split_description: 'Diese Aussage besteht aus mehr als einer Aussage und daher sollten diese getrennt werden',
    _.statement_optimization_description: 'Diese Aussage ist richtig, benötigt aber eine Korrektur bezüglich Rechtschreibung/Grammatik',
    _.argumentAdded: 'Argument wurde hinzugefügt',
    _.positionAdded: 'Position wurde hinzugefügt',
    _.statementAddedMessageContent: 'Hey {},\n\njemand hat eine Meinung zu Ihrer Aussage hinzugefügt',
    _.argumentAddedMessageContent: 'Hey {},\n\njemand hat ein Argument zu Ihrer Aussage hinzugefügt',
    _.statementIndex: 'Verfasste Aussagen - Letzte 30 Tage',
    _.statementIndexInfo: 'Anzahl an hinzugefügten Aussagen',
    _.sureThat: 'Ich bin sehr sicher, dass ',
    _.surname: 'Nachname',
    _.myStatement: 'meine Aussage',
    _.showMeAnArgumentFor: 'Zeige mir ein Argument dafür, dass',
    _.textAreaReasonHintText: 'Bitte nutzen Sie ein Feld für jeden Grund. Schreiben Sie kurz und prägnant',
    _.theCounterArgument: 'dem Gegenargument',
    _.therefore: 'Daher',
    _.thinkWeShould: 'Ich denke, wir sollten ',
    _.thisConfrontationIs: 'Dieser Angriff ist ein',
    _.textChange: 'Eine Ihrer Aussagen wurde editiert',
    _.track: 'Spur',
    _.this: 'Diese',
    _.textversionChangedTopic: 'Aussage wurde geändert',
    _.textversionChangedContent: 'Ihr Text wurde geändert von',
    _.to: 'zu',
    _.topicString: 'Thema',
    _.text: 'Text',
    _.theySay: 'Sie sagen, dass',
    _.heSays: 'Er sagt, dass',
    _.sheSays: 'Sie sagt, dass',
    _.theyThink: 'Sie denken, dass',
    _.theyThinkThat: 'Sie denken, dass',
    _.participantsThink: 'Die anderen Teilnehmer denken, dass',
    _.heThinks: 'Er denkt, dass',
    _.sheThinks: 'Sie denkt, dass',
    _.thisIsACopyOfMail: 'Dies ist eine Kopie Ihrer Mail',
    _.thisArgument: 'das Argument',

    _.theirArgument: 'deren Argument',
    _.herArgument: 'ihr Argument',
    _.hisArgument: 'sein Argument',
    _.theirStatement: 'deren Aussage',
    _.herStatement: 'ihre Aussage',
    _.hisStatement: 'seine Aussage',
    _.theirAssertion: 'deren Behauptung',
    _.herAssertion: 'ihre Behauptung',
    _.hisAssertion: 'seine Behauptung',
    _.theirPosition: 'deren Standpunkt',
    _.herPosition: 'ihr Standpunkt',
    _.hisPosition: 'sein Standpunkt',
    _.theirReason: 'deren Begründung',
    _.herReason: 'ihre Begründung',
    _.hisReason: 'seine Begründung',

    _.thxForFlagText: 'Danke für Ihre Meldung, wir kümmern uns darum',
    _.veryweak: 'sehr schwach',
    _.wantToStateNewPosition: 'Nichts von all dem. Melden Sie sich kurz an, um eine neue Idee anzugeben',
    _.weak: 'schwach',
    _.where: 'Wo',
    _.wrong: 'Nein',
    _.wouldYourShareArgument: 'Können Sie einen Grund angeben?',
    _.wrongConclusion: 'Die Kombination aus Conclusion ID und Issue ist ungültig',
    _.wrongArgument: 'Die ID des Arguments ist ungültig',
    _.wrongStatement: 'Die ID des Statements ist ungültig',
    _.wrongURL: 'Ihre URL scheint falsch zu sein.',
    _.whatDoYouThinkAbout: 'Was halten Sie von der Aussage, dass',
    _.whatDoYouThinkArgument: 'Was halten Sie von dem Argument',
    _.whatDoYouThinkOf: 'Was halten Sie von',
    _.whatDoYouThinkAboutThat: 'Was denken Sie darüber',
    _.whatIsYourIdea: 'Ich möchte darüber reden, dass',
    _.whatIsYourMostImportantReasonForArgument: 'Was ist Ihr wichtigster Grund {}für{} das Argument',
    _.whatIsYourMostImportantReasonForStatement: 'Was ist Ihr wichtigster Grund {}für{} die Aussage',
    _.whatIsYourMostImportantReasonAgainstArgument: 'Was ist Ihr wichtigster Grund {}gegen{} das Argument',
    _.whatIsYourMostImportantReasonAgainstStatement: 'Was ist Ihr wichtigster Grund {}gegen{} die Aussage',
    _.whatIsYourMostImportantReasonWhyFor: 'Was ist Ihr wichtigster Grund dafür, dass ',
    _.whatIsYourMostImportantReasonWhyAgainst: 'Was ist Ihr wichtigster Grund dagegen, dass ',
    _.whatIsYourMostImportantReasonWhyForInColor: 'Was ist Ihr wichtigster Grund <span class=\'text-success\'>dafür</span>, dass ',
    _.whatIsYourMostImportantReasonWhyAgainstInColor: 'Was ist Ihr wichtigster Grund <span class=\'text-danger\'>dagegen</span>, dass ',
    _.whyDoYouThinkThat: 'Wieso denken Sie, dass',
    _.whyAreYouDisagreeingWith: 'Warum sind Sie dagegenen, dass',
    _.whyAreYouAgreeingWith: 'Warum sind Sie dafür, dass',
    _.whyAreYouDisagreeingWithInColor: 'Warum sind Sie <span class=\'text-danger\'>dagegenen</span>, dass',
    _.whyAreYouAgreeingWithInColor: 'Warum sind Sie <span class=\'text-success\'>dafür</span>, dass',
    _.whyAreYouDisagreeingWithThat: 'Warum sind Sie anderer Meinung?',
    _.itsYou: 'Das sind Sie',
    _.youMadeA: 'Sie machten ein/e',
    _.youMadeAn: 'Sie machten ein/e',
    _.youAreAbleToReviewNow: 'Sie können nun andere Beiträge begutachten',
    _.youArgue: 'Sie argumentieren, dass',
    _.youAgreeWithThecounterargument: 'Sie stimmen dem Gegenargument zu, dass',
    _.youHaveSelectedStatement: 'Sie haben folgende Aussage gewählt',
    _.relation_undermine: 'ist ein Gegenargument für',
    _.relation_support: 'ist ein Argument für',
    _.relation_undercut: 'ist ein Gegenargument für',
    _.relation_rebut: 'ist ein Gegenargument für',
    _.uid: 'ID',
    _.unfortunatelyNoMoreArgument: 'Leider gibt es keine weiteren Argumente für',
    _.userPasswordNotMatch: 'Benutzername und/oder Passwort stimmen nicht überein',
    _.userOptions: 'Benutzeroptionen',
    _.userNotFound: 'Benutzer konnte nicht gefunden werden',
    _.userIsOAuth: 'Benutzer wurde via OAuth angemeldet (Facebook, Google, ...)',
    _.userIsNotAuthorOfStatement: 'Sie sind nicht Autor der Aussage',
    _.userIsNotAuthorOfArgument: 'Sie sind nicht Autor des Arguments',
    _.untilNowThereAreNoMoreInformation: 'Bisher haben wir keine weiteren Informationen darüber',
    _.voteCountTextFirst: 'Sie sind der/die Erste, der/die sich dafür interessiert',
    _.voteCountTextFirstM: 'Sie sind der Erste, der sich dafür interessiert',
    _.voteCountTextFirstF: 'Sie sind die Erste, die sich dafür interessiert',
    _.voteCountTextMayBeFirst: 'Sie wären der/die Erste, der/die sich dafür interessiert',
    _.voteCountTextMayBeFirstM: 'Sie wären der Erste, der sich dafür interessiert',
    _.voteCountTextMayBeFirstF: 'Sie wären die Erste, die sich dafür interessiert',
    _.voteCountTextOneOther: 'Ein/e Andere/r interessiert sich auch dafür',
    _.voteCountTextOneOtherM: 'Ein Anderer interessiert sich auch dafür',
    _.voteCountTextOneOtherF: 'Eine Andere interessiert sich auch dafür',
    _.voteCountTextMore: 'weitere Teilnehmer/innen interessieren sich auch dafür',
    _.voteCountTextOneMore: 'weitere/r Teilnehmer/innen interessieren sich auch dafür',
    _.voteCountTextOneMoreM: 'weiterer Teilnehmer interessieren sich auch dafür',
    _.voteCountTextOneMoreF: 'weitere Teilnehmerinnen interessieren sich auch dafür',
    _.visitDeleteQueue: 'Schauen Sie in die Liste für Löschanträge.',
    _.visitDeleteQueueLimitation: 'Sie brauchen mindestens {} Punkte, um sich die Löschanträge anzuschauen',
    _.visitOptimizationQueue: 'Schauen Sie in die Liste für Optimierungen.',
    _.visitOptimizationQueueLimitation: 'Sie brauchen mindestens {} Punkte, um sich die Optimierungen anzuschauen',
    _.visitEditQueue: 'Schauen Sie in die Liste für Änderungen',
    _.visitEditQueueLimitation: 'Sie brauchen mindestens {} Punkte, um sich die Änderungen anzuschauen',
    _.visitDuplicateQueue: 'Schauen Sie in die Liste für Duplikate',
    _.visitDuplicateQueueLimitation: 'Sie brauchen mindestens {} Punkte, um sich die Duplikate anzuschauen',
    _.visitSplitQueue: 'Schauen Sie in die Liste für geteilte Aussagen',
    _.visitSplitQueueLimitation: 'Sie brauchen mindestens {} Punkte, um sich die Teilungen anzuschauen',
    _.visitMergeQueue: 'Schauen Sie in die Liste für zusammengeführte Aussagen',
    _.visitMergeQueueLimitation: 'Sie brauchen mindestens {} Punkte, um sich die Zusammenführungen anzuschauen',
    _.visitHistoryQueue: 'Schauen Sie sich alle vergangenen Entscheidungen an',
    _.visitHistoryQueueLimitation: 'Sie brauchen mindestens {} Punkte, um in die Vergangenheit zu reisen',
    _.visitOngoingQueue: 'Schauen Sie sich die aktuell laufenden Entscheidungen an',
    _.welcome: 'Willkommen',
    _.welcomeMessage: 'Willkommen im neuen dialog-basierten Argumentations-System.<br>Wir wünschen viel Spaß beim Diskutieren',
    _.youHaveTheOpinionThat: 'Sie haben die Meinung, dass {}',
    _.youAreInterestedIn: 'Sie interessieren sich für',
    _.youAgreeWith: 'Sie interessiert, dass {}',
    _.youAgreeWithThatNow: 'Nun geben Sie an, dass',
    _.youDisagreeWith: 'Sie widersprechen dem Vorschlag, dass {}',
    _.youSaidThat: 'Sie haben gesagt, dass',
    _.youUsedThisEarlier: 'Sie haben diese Aussage schon benutzt',
    _.youRejectedThisEarlier: 'Sie haben diese Aussage schon abgelehnt',
    _.youHaveMuchStrongerArgumentForAccepting: 'Sie haben eine viel stärkere Begründung für',
    _.youHaveMuchStrongerArgumentForRejecting: 'Sie haben eine viel stärkere Ablehnung für',
}
