#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
German translations of the keywords

.. codeauthor:: Tobias Krauthoff <krauthoff@cs.uni-duesseldorf.de
"""
from .keywords import Keywords as _

en_lang = {
    _.arguments: 'arguments',
    _.error: 'Error',
    _.iActuallyHave: 'I actually have',
    _.insertOneArgument: 'I have one argument:',
    _.insertDontCare: 'Accept it as it is!',
    _.forgotInputRadio: 'You forgot to choose the right interpretation',
    _.needHelpToUnderstandStatement: 'We need your help to understand your statement!',
    _.setPremisegroupsIntro1: 'You have used \'and\' in your statement: ',
    _.setPremisegroupsIntro2: '. There are two ways this could be interpreted. Please help us by selecting the right interpretation:',
    _.attack: 'You disagreed with',
    _.support: 'You agreed with',
    _.premise: 'Premise',
    _.because: 'Because',
    _.moreAbout: 'More about',
    _.undermine: 'It is false that',
    _.support1: '',
    _.undercut1: 'It is false that',
    _.undercut2: 'and this is no good counter-argument',
    _.rebut1: 'It is right that',
    _.rebut2: ' but I have a better statement',
    _.oldPwdEmpty: 'Old password field is empty.',
    _.newPwdEmtpy: 'New password field is empty.',
    _.confPwdEmpty: 'Password confirmation field is empty.',
    _.newPwdNotEqual: 'New passwords are not equal',
    _.pwdsSame: 'Both entered passwords are equal.',
    _.oldPwdWrong: 'Your old password is wrong.',
    _.pwdChanged: 'Your password was changed',
    _.emptyName: 'Your name is empty!',
    _.emptyEmail: 'Your e-mail is empty!',
    _.emtpyContent: 'Your content is empty!',
    _.maliciousAntiSpam: 'Your anti-spam message is wrong. Please reload the page!',
    _.maliciousSlug: 'Malicious URL',
    _.nonValidCSRF: 'Your session is not valid',
    _.name: 'Name',
    _.mail: 'Mail',
    _.phone: 'Phone',
    _.message: 'Message',
    _.messageDeleted: 'Message deleted',
    _.notification: 'Notification',
    _.notificationDeleted: 'Notification deleted',
    _.pwdNotEqual: 'Passwords are not equal',
    _.pwdShort: 'Password is too short (at least 5 chars)',
    _.nickIsTaken: 'Nickname is taken',
    _.mailIsTaken: 'E-Mail is taken',
    _.mailNotValid: 'E-Mail is not valid',
    _.mailSettingsTitle: 'Enables/Disables e-mails',
    _.notificationSettingsTitle: 'Enables/Disables notifications',
    _.errorTryLateOrContant: 'An error occurred, please try again later or contact the administrator',
    _.accountWasAdded: 'Your account {} was added and you are now able to log in.',
    _.accountRegistration: 'D-BAS Registration',
    _.accountWasRegistered: 'Hi {} {},\n\nan account was successfully registered for mail {}.\n\nHave fun!',
    _.accoutErrorTryLateOrContant: 'Your account could not be added. Please try again or contact the author.',
    _.nicknameIs: 'Your nickname is: ',
    _.newPwdIs: 'Your new password is: ',
    _.newPwdInfo: 'If you have not requested this mail, please inform the operator.',
    _.dbasPwdRequest: 'D-BAS Password Request',
    _.antispamquestion: 'What is',
    _.defaultView: 'Default View',
    _.positions: 'Positions',
    _.labels: 'Labels',
    _.showMyPath: 'Show my path',
    _.hideMyPath: 'Hide my path',
    _.myStatements: 'My statements',
    _.myDiscussions: 'My Discussions',
    _.supportsOnMyStatements: 'Supports',
    _.attacksOnMyStatements: 'Relations',
    _.addATopic: 'Add a topic',
    _.editIssueViewChangelog: 'Edit Issues / View Changelog',
    _.editTitleHere: 'Please, edit the selected Title here:',
    _.editInfoHere: 'Please, edit the selected info here:',
    _.viewChangelog: 'View Changelog',
    _.editStatementHere: 'Please, edit the statement here:',
    _.save: 'Save',
    _.cancel: 'Cancel',
    _.submit: 'Submit',
    _.close: 'Close',
    _.urlSharing: 'Share your URL',
    _.urlSharingDescription: 'Please feel free to share this url:',
    _.warning: 'Warning',
    _.resumeHere: 'Resume here',
    _.aand: 'and',
    _.andor: 'and/or',
    _.addedEverything: 'Everything was added.',
    _.addStatementRow: 'Add another statement.',
    _.addTopic: 'Add a Topic',
    _.alreadyInserted: 'This is a duplicate and already there.',
    _.addIssueInfo: 'You need at least {} point for opening a new discussion.',
    _.addPremisesRadioButtonText: 'Let me enter my reasons!',
    _.addArgumentsRadioButtonText: 'Let me enter my own statements!',
    _.argumentContainerTextIfPremises: 'You want to state your own reasons?',
    _.argumentContainerTextIfArguments: 'You want to state your own arguments?',
    _.addPremiseRadioButtonText: 'Let me enter my reason',
    _.addArgumentRadioButtonText: 'Let me enter my own statement',
    _.argumentContainerTextIfPremise: 'You want to state your own reason?',
    _.argumentContainerTextIfArgument: 'You want to state your own argument?',
    _.argumentContainerTextIfConclusion: 'What is your idea? What should we do?',
    _.argueAgainstPositionToggleButton: 'Or do you want to argue against a position? Please toggle this button:',
    _.argueForPositionToggleButton: 'Or do you want to argue for a position? Please toggle this button:',
    _.andIDoNotBelieveCounter: 'and I do not believe that this is a good counter-argument for',
    _.andIDoNotBelieveArgument: 'and I do not believe that this is a good argument for',
    _.andTheyDoNotBelieveCounter: 'and they do not believe that this is a good counter-argument for',
    _.andTheyDoNotBelieveArgument: 'and they do not believe that this is a good argument for',
    _.argumentFlaggedBecauseOfftopic: 'This argument was reported by a participant, because it probably is <strong>off topic of the discussion</strong>.',
    _.argumentFlaggedBecauseSpam: 'This argument was reported by a participant, because it probably is <strong>spam</strong>.',
    _.argumentFlaggedBecauseHarmful: 'This argument was reported by a participant, because it probably is <strong>inappropriate, harmful or abbusive</strong>.',
    _.argumentFlaggedBecauseOptimization: 'This argument was reported by a participant, because it probably <strong>needs optimization</strong>.',
    _.argumentFlaggedBecauseEdit: 'This argument was improved from a grammatical point of view.',
    _.argumentFlaggedBecauseDuplicate: 'This statement was flagged, because maybe it is a duplicate.',
    _.argumentFlaggedBecauseSplit: 'This statement was flagged, because it should be splitted',
    _.argumentFlaggedBecauseMerge: 'This statements were flagged, because they should be joined together.',
    _.argument_optimization_description: 'This argument is acceptable but it needs correction for spelling/grammar.',
    _.argument_offtopic_or_irrelevant_description: 'This argument does not belong to the topic under discussion.',
    _.argument_statement_harmful_description: 'A reasonable person would find this content inappropriate for respectful discourse.',
    _.alternatively: 'Alternatively',
    _.addArguments: 'Add arguments',
    _.addStatements: 'Add statements',
    _.addArgumentsTitle: 'Adds new arguments',
    _.acceptItTitle: 'Accept it...',
    _.acceptIt: 'Accept it...',
    _.asReasonFor: 'as reason for',
    _.askAFriend: 'Ask a friend',
    _.argument: 'Argument',
    _.attackPosition: 'attack Position',
    _.attackStatement: 'Attack statement',
    _.at: 'at',
    _.assertion: 'assertion',
    _.accept: 'accept',
    _.assistance: 'assistance',
    _.agreeToThis0: 'Nobody agrees to this statement',
    _.agreeToThis1: 'agrees to this statement',
    _.agreeToThis2: 'agree to this statement',
    _.attackedBy: 'You were attacked by',
    _.attackedWith: 'You\'ve attacked with',
    _.agreeBecause: 'I agree because ',
    _.andIDoBelieveCounterFor: 'and I do believe that this is a counter-argument for',
    _.andIDoBelieveArgument: 'and I do believe that this is an argument for',
    _.attitudeFor: 'Attitudes for',
    _.alreadyFlaggedByOthers: 'This argument was already reported by others!',
    _.alreadyFlaggedByYou: 'You already have reported this argument/statement!',
    _.alreadyEditProposals: 'We could just accept just some of the proposals, because there are already proposals.',
    _.alreadyExecuted: 'Someone was faster, this decision is already done!',
    _.breadcrumbsStart: 'Start',
    _.breadcrumbsChoose: 'Multiple reasons for',
    _.breadcrumbsJustifyStatement: 'Why do you think that',
    _.breadcrumbsGetPremisesForStatement: 'Get premises',
    _.breadcrumbsMoreAboutArgument: 'More about',
    _.breadcrumbsReplyForPremisegroup: 'Reply for group',
    _.breadcrumbsReplyForResponseOfConfrontation: 'Justification of',
    _.breadcrumbsReplyForArgument: 'Reply for argument',
    _.bugSubmit: 'Submit your bug',
    _.butIDoNotBelieveCounterFor: 'But I do not believe that this is a counter-argument for {}',
    _.butIDoNotBelieveArgumentFor: 'But I do not believe that this is a argument for {}',
    _.butIDoNotBelieveReasonForReject: 'But I do not believe that this is a reason for reject',
    _.butTheyDoNotBelieveCounter: 'But they do {}not{} believe that this is {}a good counter-argument for{}',
    _.butSheDoesNotBelieveCounter: 'But she does {}not{} believe that this is {}a good counter-argument for{}',
    _.butHeDoesNotBelieveCounter: 'But he do {}not{} believe that this is {}a good counter-argument for{}',
    _.butTheyDoNotBelieveArgument: 'But they do {}not{} believe that this is {}a good argument for{}',
    _.butSheDoesNotBelieveArgument: 'But she does {}not{} believe that this is {}a good argument for{}',
    _.butHeDoesNotBelieveArgument: 'But he does {}not{} believe that this is {}a good argument for{}',
    _.butOtherParticipantsDontHaveOpinionRegardingYourOpinion: 'but other participants do not have any opinion regarding your selection',
    _.butOtherParticipantsDontHaveArgument: 'but other participants do not have any argument for that.',
    _.butOtherParticipantsDontHaveCounterArgument: 'but other participants do not have any counter argument for that.',
    _.butWhich: 'but which one',
    _.butThisDoesNotRejectArgument: 'But this does not rejects the argument that',
    _.butThisDoesNotRejectStatement: 'But this does not rejects the statement that',
    _.but: 'but',
    _.butYouCounteredWithInterest: 'You did not agree with this because',
    _.butYouCounteredWithArgument: 'You did not agree with this because',
    _.butYouAgreedWith: 'And you agreed with this because',
    _.canYouGiveAReason: 'Can you give a reason?',
    _.canYouGiveAReasonFor: 'Can you give a reason for',
    _.canYouGiveACounter: 'Can you give a counter-argument?',
    _.canYouGiveACounterArgumentWhy1: 'Can you give a counter-argument, why are you against',
    _.canYouGiveACounterArgumentWhy2: '?',
    _.canYouGiveAReasonForThat: 'Can you give a reason for that?',
    _.canYouBeMorePrecise: 'Can you be more precise, please? What is wrong with the conclusion?',
    _.clickHereForRegistration: 'Click <a data-toggle="modal" data-target="#popup-login" title="Login" data-href="login" >here</a> for log in or registration!',
    _.clickForMore: 'Click for more!',
    _.countOfArguments: 'Count of arguments',
    _.countOfPosts: 'Count of posts',
    _.confirmation: 'Confirmation',
    _.contact: 'Contact',
    _.contactSubmit: 'Submit your Message',
    _.conclusionIsMissing: 'Conclusion ID is missing',
    _.confirmTranslation: 'If you change the language, your process on this page will be lost and you have to restart the discussion!',
    _.correctionsSet: 'Your correction was set.',
    _.checkFirstname: 'Better check your first name, because the input is empty!',
    _.checkLastname: 'Better check your last name, because the input is empty!',
    _.checkNickname: 'Better check your nickname, because the input is empty!',
    _.checkLanguage: 'Better check your language, because the input is empty!',
    _.checkEmail: 'Better check your email, because the input is empty!',
    _.checkPassword: 'Better check your password, because the input is empty!',
    _.checkConfirmation: 'Better check the confirmation of your password, because the input is empty!',
    _.completeView: 'Complete View',
    _.completeViewTitle: 'Shows the complete graph',
    _.checkPasswordConfirm: 'Better check your passwords, because they are not equal!',
    _.clickToChoose: 'Click to choose',
    _.clearStatistics: 'Clear Statistics',
    _.congratulation: 'Congratulation!',
    _.currentDiscussion: 'Current discussion is about',
    _.description_undermine: 'This statement attacks the premise.',
    _.description_support: 'This statement supports the premise.',
    _.description_undercut: 'This statement attacks the justification (undercut). You do not believe that the premise justifies the conclusion.',
    _.description_rebut: 'This statement is against the conclusion itself.',
    _.description_no_opinion: 'You just have no opinion regarding the confrontation or you just want to skip this.',
    _.decisionIndex7: 'Clicks during a discussion - Last 7 Days',
    _.decisionIndex30: 'Clicks during a discussion - Last 30 Days',
    _.decisionIndex7Info: 'Count of made decision (due to clicks in a discussion) in the last 7 days',
    _.decisionIndex30Info: 'Count of made decision (due to clicks in a discussion) in the last 30 days',
    _.dateString: 'Date',
    _.deleteTrack: 'Delete track',
    _.deleteStatement: 'Delete statement',
    _.disassociateStatement: 'Disassociate from statement',
    _.deleteHistory: 'Delete history',
    _.delete: 'Delete',
    _.disagreeBecause: 'I disagree because ',
    _.dataRemoved: 'Data was successfully removed.',
    _.didYouMean: 'Top10 statements, which you probably could mean:',
    _.dialogView: 'Dialog View',
    _.dialogViewTitle: 'Show the dialog View',
    _.displayControlDialogGuidedTitle: 'Dialog View',
    _.displayControlDialogGuidedBody: 'You will never see something like an argumentation map, because the systems seems to be like a dynamic and generic.',
    _.displayControlDialogIslandTitle: 'Island View',
    _.displayControlDialogIslandBody: 'Okay, you want to see more as, but not everything. Therefore the island view will present you a list of every connected statement for an specific statement.',
    _.displayControlDialogExpertTitle: 'Expert View',
    _.displayControlDialogExpertBody: 'So, you think you are an expert? Okay, you can have a view of the complete argumentation map',
    _.displayControlDialogGraphTitle: 'Graph-View',
    _.displayControlDialogGraphBody: 'Presentation of the discusion as graph.',
    _.discussionEnd: 'The discussion ends here.',
    _.discussionStart: 'Discussions Overview',
    _.discussionEndAndReadOnly: 'The discussion ends here. Unfortunately the discussion was set as read only, so that no new statements can be added.',
    _.discussionCongratulationEnd: 'The discussion ends here, because there is no other counter argument at the moment.',
    _.discussionEndLinkTextLoggedIn: 'You can restart the discussion with the button above.',
    _.discussionEndLinkTextNotLoggedIn: 'You can restart the discussion with the button above.',
    _.discussionEndLinkTextWithQueueLoggedIn: 'Are you looking for things to do? Take a look at the <a id="discussionEndReview">review section</a>. Alternatively you can restart the discussion with the button above.',
    _.discussionEndLinkTextWithQueueNotLoggedIn: 'Are you looking for things to do? <a  data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">Login</a> and take a look at the <a id="discussionEndReview">review section</a>. Alternatively you can restart the discussion with the button above.',
    _.discussionInfoTooltipSg: 'The discussion was started at {} {} and has just {} argument. Come and join in!',
    _.discussionInfoTooltipPl: 'The discussion was started at {} {} and already has {} arguments.',
    _.discussionIsReadOnly: 'Discussion is read only.',
    _.disagreeToThis0: 'Nobody disagree to this statement',
    _.disagreeToThis1: 'disagrees to this statement',
    _.disagreeToThis2: 'disagree to this statement',
    _.duplicate: 'Duplikat',
    _.duplicateDialog: 'This textversion is deprecated, because it was already edited to this version.\nDo you want to set this version as the current one once again?',
    _.doesNotHold: 'does not hold',
    _.isNotRight: 'does not hold',
    _.isNoGoodJustification: 'is not a good justification',
    _.issueEnableDescription: 'Indicates, whether the topic is available.',
    _.issuePublicDescription: 'Indicates, whether the topic is available for everyone or just via invite with a link (private).',
    _.issueWritableDescription: 'Indicates, whether statements can be written or the topic is read only.',
    _.doNotHesitateToContact: 'Do not hesitate to <span style="cursor: pointer;" id="contact-on-error"><strong>contact us (click here)</strong></span>',
    _.docs: 'Documentation',
    _.doesJustify: 'does justify that',
    _.doesNotJustify: 'does not justify that',
    _.doYouWantToEnterYourStatements: 'Do you want to enter your statement(s)?',
    _.dataNowLocked: 'You locked the data.',
    _.dataUnlocked: 'Data unlocked!',
    _.dataAlreadyLockedByYou: 'You are already editing data. Please exit your work first!',
    _.dataAlreadyLockedByOthers: 'Sorry, this data edited by other participants.',
    _.earlierYouArguedThat: 'Earlier you argued that',
    _.eachStatement: 'per Statement',
    _.editIndex: 'Count of given reviews - Last 30 Tage',
    _.editIndexInfo: 'Count of Edits',
    _.editTextMessage: 'Your original statement was edited by {}\nFrom: {}\nTo: {}\nWhere: {}',
    _.editTextMessageForHtml: 'Your original statement was edited by {}<br>From: {}<br>To: {}<br>Where: <a href="{}">{}</a>',
    _.euCookiePopupTitle: 'This website is using cookies and Matomo.',
    _.euCookiePopupText: 'We use them to give you the best experience. If you continue using our website, we\'ll assume that you are happy to receive all cookies on this website and being tracked for academic purpose. All tracked data are saved anonymously with reduced masked IP-addresses.',
    _.euCookiePopoupButton1: 'Continue',
    _.euCookiePopoupButton2: 'Learn&nbsp;more',
    _.empty_news_input: 'News title or text is empty or too short!',
    _.empty_notification_input: 'Notification title or text is empty or too short!',
    _.email: 'E-Mail',
    _.emailWasSent: 'E-Mail was sent.',
    _.emailWasNotSent: 'E-Mail was not sent.',
    _.emailUnknown: 'The given mail address is unknown.',
    _.emailBodyText: 'This is an automatically generated mail by D-BAS {}.\nFor contact please write a mail to dbas@cs.uni-duesseldorf.de\nThis system is part of a doctoral thesis.',
    _.emailArgumentAddTitle: 'D-BAS Information about an Argument',
    _.emailArgumentAddBody: 'New statements were added to your argument. Have a look at:',
    _.exampleName: 'example: Tobias Krauthoff',
    _.exampleMail: 'example: krauthoff@cs.uni-duesseldorf.de',
    _.examplePhone: 'example: +49 (0)211 81-13461',
    _.exampleMessage: 'example: I\'d like to say good job!',
    _.exampleMessageBug: 'example: On url https://dbas.cs.uni-duesseldorf.de/discuss/a/b D-BAS behaves strange, because ...',
    _.exampleNickname: 'example: Democrator',
    _.examplePassword: 'example: ********',
    _.exampleNicknameLdap: 'example: tokra100',
    _.exampleFirstname: 'example: Tobias',
    _.exampleLastname: 'example: Krauthoff',
    _.exampleStatement: 'Please enter the source here',
    _.exampleSource: 'Please enter the cite here',
    _.exampleSearchDuplicate: 'Enter parts of the statement to search',
    _.examplePosition: 'we should do something',
    _.exampleReason: 'this is a reason for it',
    _.exampleAddTopicTitle: 'e.g.: Cat or Dog',
    _.exampleAddTopicQuestion: 'e.g.: Your family argues about buying a cat or dog. What is your position?',
    _.exampleAddTopicDescription: 'e.g.: In the last days your family talked about the buy of a new pet. Currently they are argueing whether to buy a cat or dog. Nor your opininion matters!',
    _.everythingSaved: 'Everything saved!',
    _.opinionSaved: 'Your opinion was saved!',
    _.error_code: 'Error code',
    _.edit: 'Edit',
    _.editTitle: 'Edit statement',
    _.editAlreadyTitle: 'This statement was already edited and will be reviewed by the crowd.',
    _.feelFreeToLogin: 'If you want to proceed, please feel free to <a  data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">login</a>.',
    _.forText: 'for',
    _.forThat: 'accept that',
    _.firstConclusionRadioButtonText: 'Let me enter my idea!',
    _.firstArgumentRadioButtonText: 'Let me enter my own statement(s)!',
    _.feelFreeToShareUrl: 'Please feel free to share this url',
    _.fetchLongUrl: 'Long URL',
    _.fetchShortUrl: 'Short URL',
    _.forgotPassword: 'Forgot Password',
    _.firstOneInformationText: 'You are the first one, who is interested in: {}.',
    _.firstOneInformationTextM: 'You are the first one, who is interested in: {}.',
    _.firstOneInformationTextF: 'You are the first one, who is interested in: {}.',
    _.firstOneReason: 'You are the first one with this argument, please give a reason.',
    _.firstOneReasonM: 'You are the first one with this argument, please give a reason.',
    _.firstOneReasonF: 'You are the first one with this argument, please give a reason.',
    _.firstPositionText: 'You are the first one in this discussion!',
    _.firstPositionTextM: 'You are the first one in this discussion!',
    _.firstPositionTextF: 'You are the first one in this discussion!',
    _.firstPremiseText1: 'You are the first one, who said that',
    _.firstPremiseText1M: 'You are the first one, who said that {}',
    _.firstPremiseText1F: 'You are the first one, who said that {}',
    _.firstPremiseText2: 'Please enter your reason for your statement.',
    _.firstname: 'First name',
    _.fillLine: 'Please, fill this this line with your report',
    _.finish: 'Finish',
    _.finishTitle: 'Leave the discussion!',
    _.fieldtest: 'Field Experiment',
    _.fromm: 'from',
    _.gender: 'Gender',
    _.goBack: 'Click to go back',
    _.goHome: 'Go home',
    _.goStepBack: 'Go one step back',
    _.generateSecurePassword: 'Generate secure password',
    _.goodPointTakeMeBackButtonText: 'I agree, that is a good argument! Take me one step back.',
    _.group_uid: 'Group',
    _.goBackToTheDiscussion: 'Go back to the discussion',
    _.goForward: 'Click to go forward',
    _.goodPointAndUserIsInterestedTooM: '{}This is a good point and{} {} {}is interested in your conclusion too. He says, that{} {}.',
    _.goodPointAndUserIsInterestedTooF: '{}This is a good point and{} {} {}is interested in your conclusion too. She says, that{} {}.',
    _.goodPointAndOtherParticipantsIsInterestedToo: '{}This is a good point and other participants are interested in your conclusion too. They say, that{} {}.',
    _.haveALookAt: 'Hey, please have a look at ',
    _.hidePasswordRequest: 'Hide Password Request',
    _.hideGenerator: 'Hide Generator',
    _.hold: 'hold',
    _.howeverIHaveMuchStrongerArgumentRejectingThat: 'However, I have a much stronger argument for reject that',
    _.howeverIHaveMuchStrongerArgumentAcceptingThat: 'However, I have a much stronger argument for accept that',
    _.howeverIHaveMuchStrongerArgument: 'However, I have a much stronger argument',
    _.howeverIHaveMuchStrongerArgumentTo: 'However, I have a much stronger argument to',
    _.howeverIHaveEvenStrongerArgumentRejecting: 'However, I have an even stronger argument for reject that',
    _.howeverIHaveEvenStrongerArgumentAccepting: 'However, I have an even stronger argument for accept that',
    _.imprint: 'Imprint',
    _.iAgreeWithInColor: 'I <span class=\'text-success\'>agree</span>',
    _.iAgreeWith: 'I agree ',
    _.iDisagreeWithInColor: 'I <span class=\'text-danger\'>disagree</span>',
    _.iDisagreeWith: 'I disagree',
    _.iDoNotKnow: 'I do not know',
    _.iDoNotKnowInColor: 'I <span class=\'text-info\'>do not know</span>',
    _.iHaveNoOpinionYet: 'I have no opinion yet about',
    _.iHaveNoOpinion: 'I have no opinion',
    _.iHaveNoOpinionYetInColor: 'I have <span class=\'text-info\'>no opinion yet</span>, show me an argument',
    _.informationForExperts: 'Information for experts',
    _.invalidTableName: 'Invalid table name',
    _.internalFailureWhileDeletingTrack: 'Internal failure, please try again or did you have deleted your track recently?',
    _.internalFailureWhileDeletingHistory: 'Internal failure, please try again or did you have deleted your history recently?',
    _.internalError: '<strong>Internal Error:</strong> Maybe the server is offline.',
    _.internalErrorHTTPS: 'Internal error due to the login process',
    _.internalKeyError: 'Internal error while reading input data.',
    _.issueList: 'Topics',
    _.issueNotFound: 'No issue found',
    _.irrelevant: 'Irrelevant',
    _.itIsTrueThat: 'it is true that',
    _.maybeItIsTrueThat: 'Maybe it is true that',
    _.itIsTrueThatAnonymous: 'it is true that',
    _.itIsTrue1: ' ',
    _.itIsTrue2: ' is true',
    _.itIsFalseThat: 'it is false that',
    _.itIsFalseThatAnonymous: 'it is false that',
    _.itIsFalse1: '  ',
    _.itIsFalse2: 'is false',
    _.itTrueIsThat: 'it is true that ',
    _.itFalseIsThat: 'it is false that ',
    _.isFalse: 'is false',
    _.isNotAGoodIdea: 'is not a good idea',
    _.isNotAGoodReasonFor: 'is not a good reason for',
    _.isNotAGoodReasonAgainstArgument: 'is not a good reason against the argument that',
    _.itIsNotRight: 'is not a good idea ',
    _.isNotAGoodIdeaInColor: '<span class=\'text-danger\'>is not a good idea</span>',
    _.isTrue: 'is true',
    _.areTrue: 'are true',
    _.initialPositionInterest: 'I want to talk about the position that',  # What is the initial position you are interested in?'
    _.invalidEmail: 'Your mail is invalid!',
    _.iAcceptCounter: 'and I do accept that this is a counter-argument for',
    _.iAcceptArgument: 'and I do accept that this is an argument for',
    _.iAcceptCounterThat: 'and I do accept that this is a counter-argument for',
    _.iAcceptArgumentThat: 'and I do accept that this is an argument for',
    _.iHaveMuchStrongerArgumentRejecting: 'I have a much stronger argument for reject that',
    _.iHaveEvenStrongerArgumentRejecting: 'I have an even stronger argument for reject that',
    _.iHaveMuchStrongerArgumentAccepting: 'I have a much stronger argument for accept that',
    _.iHaveEvenStrongerArgumentAccepting: 'I have an even stronger argument for accept that',
    _.iNoOpinion: 'I have no opinion regarding',
    _.interestingOnDBAS: 'Interesting discussion on DBAS',
    _.inputEmpty: 'Input is empty!',
    _.informationForStatements: 'Information of the statements',
    _.relativePopularityOfStatements: 'Relative popularity of Statements',
    _.jumpAnswer0: 'Right, I support the {} and accept the {}.',
    _.jumpAnswer1: 'Right, I support the {}, but I want to add my own {}.',
    _.jumpAnswer2: 'Right, I support the {}, but the {} does not support it.',
    _.jumpAnswer3: 'Wrong, the {} is false.',
    _.jumpAnswer4: 'Wrong, the {} does not hold.',
    _.supportAnswer0: 'I accept the {}.',
    _.supportAnswer1: 'I want to add a new {}.',
    _.supportAnswer2: 'The {} does not support the {}.',
    _.supportAnswer3: 'The {} does not hold.',
    _.justLookDontTouch: 'Just look, do not touch anything!',
    _.keyword: 'Keyword',
    _.keywordStart: 'Start',
    _.keywordChooseActionForStatement: 'Choosing attitude',
    _.keywordGetPremisesForStatement: 'Getting premises',
    _.keywordMoreAboutArgument: 'More about',
    _.keywordReplyForPremisegroup: 'Reply for argument',
    _.keywordReplyForResponseOfConfrontation: 'Justification of',
    _.keywordReplyForArgument: 'Confrontation',
    _.keepSetting: 'Keep this',
    _.holds: 'holds',
    _.holdsInColor: '<span class=\'text-success\'>holds</span>',
    _.hideAllUsers: 'Hide all users',
    _.hideAllAttacks: 'Hide all attacks',
    _.letMeExplain: 'Let me explain it this way',
    _.levenshteinDistance: 'Levenshtein-Distance',
    _.languageCouldNotBeSwitched: 'Unfortunately, the language could not be switched',
    _.last_action: 'Last Action',
    _.last_login: 'Last Login',
    _.login: 'Login',
    _.logfile: 'Logfile for',
    _.letsGo: 'Click here to start now!',
    _.letsGoBack: 'Let\'s go back!',
    _.letsGoHome: 'Let\'s go home!',
    _.langNotFound: 'Language not found',
    _.latestNewsFromDiscussion: 'Latest news about actions in the discussion',
    _.latestNewsFromDBAS: 'Latest news about D-BAS, a Dialog-Based Argumentation System',
    _.ldapInfo: 'We are using the register of persons of the Uni Düsseldorf. All data and information are of course sent SSL encrypted and will never be passed on to any third parties after receipt.',
    _.more: 'More',
    _.medium: 'medium',
    _.minLength: 'Minimal length',
    _.myArgument: 'my argument',
    _.mark_as_opinion: 'Click to mark this as your opinion',
    _.unmark_as_opinion: 'Click to remove this as your opinion',
    _.user_is_admin: 'Your panelist is an admin.',
    _.user_is_special: 'Your panelist is something special.',
    _.user_is_author: 'Your panelist is a news author.',
    _.next: 'Next Entry',
    _.now: 'Now',
    _.nowYouSayThat: 'Now you say that',
    _.newNotification: 'You got a new notification.',
    _.newMention: 'You are mentioned in a contribution.',
    _.newPremiseRadioButtonText: 'None of the above! Let me state my own reason!',
    _.newPremiseRadioButtonTextAsFirstOne: 'Let me state my own reason!',
    _.newConclusionRadioButtonText: 'Neither of the above, I have a different idea!',
    _.newConclusionRadioButtonTextNewIdea: 'I have a new idea!',
    _.newsAboutDbas: 'News about D-BAS',
    _.nickname: 'Nickname',
    _.noOtherAttack: 'The system has no other counter-argument',
    _.noCorrections: 'No valid corrections for the given statement could be fetched.',
    _.noCorrectionsSet: 'Correction could not be set, because your user was not fount in the database. Are you currently logged in?',
    _.noDecisionDone: 'No decision was done.',
    _.noDataSelected: 'No data selected',
    _.notInsertedErrorBecauseEmpty: 'Your idea was not inserted, because your text is too short or empty.',
    _.notInsertedErrorBecauseDuplicate: 'Your idea was not inserted, because your idea is a duplicate.',
    _.notInsertedErrorBecauseUnknown: 'Your idea was not inserted due to an unknown error.',
    _.notInsertedErrorBecauseInternal: 'Your idea was not inserted due to an internal error.',
    _.noEntries: 'No entries',
    _.noTrackedData: 'No data was tracked.',
    _.number: 'No',
    _.note: 'Note',
    _.no_entry: 'No entry',
    _.no_arguments: 'No arguments for this opinion',
    _.noRights: 'You have no rights for this action!',
    _.notLoggedIn: 'You are not logged in.',
    _.on: 'On',
    _.of: 'of',
    _.off: 'Off',
    _.opinion_his: 'his opinion',
    _.opinion_her: 'her opinion',
    _.opinion: 'the opinion',
    _.onlyOneItem: 'If you want to state a new reason, please click here to log in.',
    _.onlyOneItemWithLink: 'If you want to state a new reason, please click <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">here</a> to log in.',
    _.unfortunatelyOnlyOneItem: 'Unfortunately you only have one option to choose. If you want to state a new reason, please click <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">here</a> to log in.',
    _.otherParticipantsConvincedYouThat: 'Other participants convinced you that',
    _.otherParticipantsThinkThat: 'Other participants think that',
    _.otherParticipantsAgreeThat: 'Other participants agree that',
    _.otherParticipants: 'Other participants agree that',
    _.thinkThat: 'think that',
    _.agreeThat: 'agree that',
    _.thinksThat: 'thinks that',
    _.agreesThat: 'agrees that',
    _.that: 'that',
    _.earlierYouHadNoOpinitionForThisStatement: 'earlier you had no opinion for {}',
    _.whichConfirmedYourView: 'which {}confirmed your view{}.',
    _.otherUserDoesntHaveOpinionForThisStatement: 'does not have any opinion for {}.',
    _.otherParticipantsDontHaveOpinionForThisStatement: 'Other participants do not have any opinion for this statement.',
    _.otherParticipantsDontHaveOpinion: 'Other participants do not have any opinion regarding',
    _.otherParticipantsDontHaveOpinionRegaringYourSelection: 'Other participants do not have any opinion regarding your selection',
    _.otherParticipantsDontHaveCounterForThat: 'Other participants do not have any counter-argument for that',
    _.otherParticipantsDontHaveNewCounterForThat: 'Other participants do not have any new counter-argument for that. You already have seen all other counter-arguments.',
    _.otherParticipantsDontHaveCounter: 'Other participants do not have any counter-argument for ',
    _.otherParticipantsDontHaveArgument: 'Other participants do not have any argument for ',
    _.otherParticipantsAcceptBut: 'Other participants accept your argument, but',
    _.otherParticipantDisagreeThat: 'Other participants disagree that ',
    _.otherUsersClaimStrongerArgumentS: 'claims to have a stronger statement to {}',
    _.otherUsersClaimStrongerArgumentP: 'Other participants claim to have a stronger statement to {}',
    _.claimsStrongerArgumentRejecting: 'claims to have a stronger statement for reject',
    _.claimsStrongerArgumentAccepting: 'claims to have a stronger statement for accept',
    _.otherUsersHaveCounterArgument: 'Other participants have the counter-argument that',
    _.otherUsersSaidThat: 'Other participants said that',
    _.thenOtherUsersSaidThat: 'Then other participants said that',
    _.opinionBarometer: 'Opinion Barometer',
    _.pleaseAddYourSuggestion: 'Please add your suggestion!',
    _.pleaseTryAgainLaterOrContactUs: 'Please try again later!',
    _.premiseGroup: 'PremiseGroup',
    _.premisegroupPopupWarning: 'Warning: This step cannot be made undone!',
    _.previous: 'Previous Entry',
    _.publicNickTitle: 'Enables/Disables the real nickname on your public page.',
    _.passwordSubmit: 'Change Password',
    _.preferredLangTitle: 'Preferred language for all notifications/mails',
    _.priv_access_optimization_queue: 'Access to the optimization queue',
    _.priv_access_delete_queue: 'Access to the delete queue',
    _.priv_access_edit_queue: 'Access to the edit queue',
    _.priv_access_duplicate_queue: 'Access to the duplicate queue',
    _.priv_access_split_queue: 'Access to the split queue',
    _.priv_access_merge_queue: 'Access to the merge queue',
    _.priv_access_history_queue: 'Access to all reviews of the past',
    _.priv_access_ongoing_queue: 'Access to all ongoing reviews',
    _.privacy_policy: 'Privacy Policy',
    _.premiseAndConclusionAreEqual: 'Premise and conclusion are equal',
    _.publications: 'Publications',
    _.queueDelete: 'Deletes',
    _.queueOptimization: 'Optimizations',
    _.queueEdit: 'Edits',
    _.queueDuplicate: 'Duplicates',
    _.queueHistory: 'History',
    _.queueOngoing: 'Ongoing',
    _.queueSplit: 'Splits',
    _.queueMerge: 'Merge',
    _.requestPassword: 'Request Password',
    _.myPosition: 'my point of view',
    _.myPositionGenitiv: 'my point of view ',
    _.the_der: 'the',
    _.the_die: 'the',
    _.the_das: 'the',
    _.reference: 'Reference',
    _.registered: 'Registered',
    _.restartDiscussion: 'Restart Discussion',
    _.restartDiscussionTitle: 'Restart Discussion',
    _.restartOnError: 'Please try to reload this page or restart the discussion, if reloading does not fix the problem.',
    _.recipient: 'Recipient',
    _.recipientNotFound: 'Recipient not found!',
    _.report: 'Report',
    _.reportStatement: 'Report statement',
    _.reportArgument: 'Report argument',
    _.reportIssue: 'Report Issue',
    _.review: 'Review',
    _.review_history: 'Review History',
    _.review_ongoing: 'Current Reviews',
    _.reputation: 'Reputation',
    _.right: 'Right',
    _.reason: 'reason',
    _.requestTrack: 'Request track',
    _.refreshTrack: 'Refresh track',
    _.requestHistory: 'Request history',
    _.refreshHistory: 'Refresh history',
    _.requestFailed: 'Request failed',
    _.reject: 'reject',
    _.rejection: 'rejection',
    _.remStatementRow: 'Removes this row.',
    _.reaction: 'Reactions',
    _.attitudesOfOpinions: 'Attitudes of the Opinions',
    _.reactionFor: 'Reactions for',
    _.agreeVsDisagree: 'Agree vs. Disagree',
    _.rep_reason_first_argument_click: 'You choose your first argument.',
    _.rep_reason_first_confrontation: 'You survived your first confrontation',
    _.rep_reason_first_position: 'You entered a new position for the first time',
    _.rep_reason_first_justification: 'You entered a new justification for the first time',
    _.rep_reason_first_new_argument: 'You entered a new argument for the first time',
    _.rep_reason_new_statement: 'For any argument you entered after your first one',
    _.rep_reason_success_flag: 'You have successfully marked an argument',
    _.rep_reason_success_edit: 'You have successfully edited an argument',
    _.rep_reason_success_duplicate: 'You have successfully reported an argument as duplicate',
    _.rep_reason_bad_flag: 'You misused the flag function',
    _.rep_reason_bad_edit: 'You made a bad edit',
    _.rep_reason_bad_duplicate: 'You reported an argument as duplicate, but it is not',

    _.reaction_text_undermine: 'In my opinion, {} is wrong and I would like to argue against it.',
    _.reaction_text_support: 'In my opinion, {} is correct and it convinced me.',
    _.reaction_text_undercut: 'In my opinion, {} is correct, but it does not support {}.',
    _.reaction_text_undercut_for_dont_know: 'In my opinion, {} is correct, but it is not supported by the {}.',
    _.reaction_text_rebut: 'In my opinion, {} is correct and it supports {}. However I want to defend {}.',
    _.reaction_text_rebut_for_dont_know: 'In my opinion, {} is wrong and I would like to argue against it.',

    _.questionTitle: 'Get more information about the statement!',
    _.saveMyStatement: 'Save my Statement!',
    _.selectStatement: 'Please select a statement!',
    _.selectMultipleStatementsWhichFlag: 'You have selected a linking of statements. Which one should be reported?',
    _.showAllUsers: 'Show all users',
    _.showAllArguments: 'Show all arguments',
    _.showAllArgumentsTitle: 'Show all arguments, done by users',
    _.showAllUsersTitle: 'Show all users, which are registered',
    _.supportPosition: 'support position',
    _.supportsNot: 'does not support',
    _.isupport: 'I support',
    _.strength: 'Strength',
    _.strong: 'strong',

    _.strongerStatementF: 'But she claims to have a stronger {}statement for {}{}',
    _.strongerStatementM: 'But he claims to have a stronger {}statement for {}{}',
    _.strongerStatementP: 'But they claim to have a stronger {}statement for {}{}',
    _.strongerStatementY: 'But you had a stronger {}statement for {}{}',
    _.accepting: 'accepting',
    _.rejecting: 'rejecting',
    _.strongerStatementEnd: '   ',

    _.search: 'Search',
    _.searchForStatements: 'Search for statements',
    _.serviceNotAvailable: 'Service currently not available',
    _.someoneArgued: 'Someone argued that',
    _.soYouEnteredMultipleReasons: 'So you entered multiple reasons',
    _.soYourOpinionIsThat: 'So your opinion is that',
    _.soYouWantToArgueAgainst: 'So you want to counter-argue against',
    _.shortenedBy: 'which was shortened with',
    _.shareUrl: 'Share Link',
    _.showMeAnotherArgument: 'Show me another argument',
    _.switchDiscussion: 'Change the discussion\'s topic',
    _.switchDiscussionTitle: 'Switch Discussion',
    _.switchDiscussionText1: 'If you accept, you will change the topic of the discussion to',
    _.switchDiscussionText2: 'and the discussion will be restarted.',
    _.switchLanguage: 'Switch Language',
    _.statement: 'Statement',
    _.statementAdded: 'Statement was added',
    _.statementIsAbout: 'Statement is about',
    _.statementAbout: 'Statement about',
    _.statementIsDuplicate: 'Statement is duplicate',
    _.statementsShowAll: 'Show all answers',
    _.statementsHideAll: 'Hide all answers',
    _.statement_offtopic_or_irrelevant_description: 'This statement does not belong to the topic under discussion.',
    _.statement_duplicate_description: 'This statement has been done before in a slightly different wording.',
    _.statement_merge_description: 'This statement belongs to another statement, so they should be merged.',
    _.statement_split_description: 'This statement contains more than one message and has to be splitted.',
    _.statement_optimization_description: 'Die Aussage ist richtig, sollte aber sprachlich/grammatikalisch verbessert werden.',
    _.settings: 'Settings',
    _.senderReceiverSame: 'Sender and reveicer are equal',
    _.seperated: 'seperated',
    _.argumentAdded: 'Argument was added',
    _.positionAdded: 'Position was added',
    _.statementAddedMessageContent: 'Hey, someone has added his/her opinion regarding your argument!',
    _.argumentAddedMessageContent: 'Hey, someone has added his/her argument regarding your argument!',
    _.statementIndex: 'Written statements - Last 30 Days',
    _.statementIndexInfo: 'Count of added Statements',
    _.sureThat: 'I\'m reasonably sure that ',
    _.surname: 'Surname',
    _.myStatement: 'my statement',
    _.showMeAnArgumentFor: 'Show me an argument for',
    _.textAreaReasonHintText: 'Please use a new text area for every reason, write short and clear!',
    _.theCounterArgument: 'the counter-argument',
    _.therefore: 'Therefore',
    _.thinkWeShould: 'I think we should ',
    _.track: 'Track',
    _.this: 'this',
    _.textversionChangedTopic: 'Statement was edited',
    _.textversionChangedContent: 'Your original statement was edited by',
    _.to: 'to',
    _.history: 'History',
    _.topicString: 'Topic',
    _.text: 'Text',
    _.theySay: 'They say',
    _.heSays: 'He says',
    _.sheSays: 'She says',
    _.theyThink: 'They think',
    _.theyThinkThat: 'They think that',
    _.participantsThink: 'Other participants think that',
    _.heThinks: 'He thinks that',
    _.sheThinks: 'She thinks that',
    _.thisIsACopyOfMail: 'This is a copy of your mail',
    _.thisConfrontationIs: 'This confrontation is a',
    _.thisArgument: 'this argument',

    _.theirArgument: 'their argument',
    _.hisArgument: 'his argument',
    _.herArgument: 'her argument',
    _.theirStatement: 'their statement',
    _.hisStatement: 'his statement',
    _.herStatement: 'her statement',
    _.theirAssertion: 'their assertion',
    _.herAssertion: 'her assertion',
    _.hisAssertion: 'his assertion',
    _.theirPosition: 'their point of view',
    _.hisPosition: 'his point of view',
    _.herPosition: 'her point of view',
    _.theirReason: 'their reason',
    _.herReason: 'her reason',
    _.hisReason: 'his reason',

    _.textChange: 'Some statement of yours was edited.',
    _.thxForFlagText: 'Thanks for reporting, we will have a look at it!',
    _.veryweak: 'very weak',
    _.wantToStateNewPosition: 'If you want to state a new position, please click here to log in.',
    _.weak: 'weak',
    _.wrong: 'Wrong',
    _.where: 'Where',
    _.wouldYourShareArgument: 'Would you share your argument?',
    _.whatDoYouThinkAbout: 'What do you think about',
    _.whatDoYouThinkArgument: 'What do you think about',
    _.whatDoYouThinkOf: 'What do you think of',
    _.whatDoYouThinkAboutThat: 'What do you think about that',
    _.whatIsYourIdea: 'I want to talk about the position, that',
    _.whatIsYourMostImportantReasonForArgument: 'What is your most important reason {}for{}',
    _.whatIsYourMostImportantReasonForStatement: 'What is your most important reason {}for{}',
    _.whatIsYourMostImportantReasonAgainstArgument: 'What is your most important reason {}against{}',
    _.whatIsYourMostImportantReasonAgainstStatement: 'What is your most important reason {}against{}',
    _.whatIsYourMostImportantReasonWhyFor: 'What is your most important reason why',
    _.whatIsYourMostImportantReasonWhyAgainst: 'What is your most important reason why',
    _.whatIsYourMostImportantReasonWhyForInColor: 'What is your most important reason why',
    _.whatIsYourMostImportantReasonWhyAgainstInColor: 'What is your most important reason why',
    _.whyDoYouThinkThat: 'Why do you think that',
    _.wrongURL: 'Your URL seems to be wrong.',
    _.wrongConclusion: 'The combination of conclusion id and issue does not match.',
    _.wrongArgument: 'The arguments ID is not valid.',
    _.wrongStatement: 'The statements ID is not valid.',
    _.whyAreYouDisagreeingWith: 'Why are you disagreeing with',
    _.whyAreYouAgreeingWith: 'Why are you agreeing with',
    _.whyAreYouDisagreeingWithInColor: 'Why are you <span class=\'text-danger\'>disagreeing</span> with',
    _.whyAreYouAgreeingWithInColor: 'Why are you <span class=\'text-success\'>agreeing</span> with',
    _.whyAreYouDisagreeingWithThat: 'Why are you disagreeing with that?',
    _.itsYou: 'It\'s you',
    _.youMadeA: 'You made a',
    _.youMadeAn: 'You made an',
    _.youHaveSelectedStatement: 'You have selected the statement',
    _.relation_undermine: 'is a counter-argument for',
    _.relation_support: 'is a reason for',
    _.relation_undercut: 'is a counter-argument for',
    _.relation_rebut: 'is a counter-argument for',
    _.uid: 'ID',
    _.unfortunatelyNoMoreArgument: 'Unfortunately there are no more arguments about',
    _.userPasswordNotMatch: 'User / Password do not match',
    _.userOptions: 'Users Options',
    _.userNotFound: 'User not found',
    _.userIsOAuth: 'User was logged in via OAuth (Google, Facebook, ...)',
    _.userIsNotAuthorOfStatement: 'You are not the author of this statement',
    _.userIsNotAuthorOfArgument: 'You are not the author of this argument',
    _.untilNowThereAreNoMoreInformation: 'Until now we do not have more information.',
    _.voteCountTextFirst: 'You are the first one with this decision',
    _.voteCountTextFirstM: 'You are the first one with this decision',
    _.voteCountTextFirstF: 'You are the first one with this decision',
    _.voteCountTextMayBeFirst: 'You would be the first one with this decision',
    _.voteCountTextMayBeFirstM: 'You would be the first one with this decision',
    _.voteCountTextMayBeFirstF: 'You would be the first one with this decision',
    _.voteCountTextOneOther: 'One other participant with this decision',
    _.voteCountTextOneOtherM: 'One other participant with this decision',
    _.voteCountTextOneOtherF: 'One other participant with this decision',
    _.voteCountTextMore: 'more participants with this decision',
    _.voteCountTextOneMore: ' participant with this decision',
    _.voteCountTextOneMoreM: ' participant with this decision',
    _.voteCountTextOneMoreF: ' participant with this decision',
    _.visitDeleteQueue: 'Visit the delete queue of D-BAS.',
    _.visitDeleteQueueLimitation: 'You need at least {} reputation points to review deletes.',
    _.visitEditQueue: 'Visit the edit queue of D-BAS.',
    _.visitDuplicateQueue: 'Visit the duplicate queue of D-BAS.',
    _.visitDuplicateQueueLimitation: 'You need at least {} reputation points to review duplicates.',
    _.visitEditQueueLimitation: 'You need at least {} reputation points to review edits.',
    _.visitOptimizationQueue: 'Visit the optimization queue of D-BAS.',
    _.visitOptimizationQueueLimitation: 'You need at least {} reputation points to review optimizations.',
    _.visitSplitQueue: 'Visit the split queue of D-BAS.',
    _.visitSplitQueueLimitation: 'You need at least {} reputation points to review splitted statements.',
    _.visitMergeQueue: 'Visit the merge queue of D-BAS.',
    _.visitMergeQueueLimitation: 'You need at least {} reputation points to review merged statements.',
    _.visitHistoryQueue: 'Visit the history of reviews of D-BAS.',
    _.visitHistoryQueueLimitation: 'You need at least {} reputation points to have a look into the past.',
    _.visitOngoingQueue: 'Visit the current ongoing reviews of D-BAS.',
    _.welcome: 'Welcome',
    _.welcomeMessage: 'Welcome to the novel dialog-based argumentation system.<br>We hope you enjoy using this system and happy arguing!',
    _.youAreInterestedIn: 'You are interested in',
    _.youHaveTheOpinionThat: 'You have the opinion that {}',
    _.youAgreeWith: 'You agree with {}',
    _.youAgreeWithThatNow: 'Now you agree that',
    _.youDisagreeWith: 'You disagree with: {}',
    _.youSaidThat: 'You said that',
    _.youUsedThisEarlier: 'You used this earlier',
    _.youRejectedThisEarlier: 'You rejected this earlier',
    _.youHaveMuchStrongerArgumentForAccepting: 'You have a much stronger argument for accept',
    _.youHaveMuchStrongerArgumentForRejecting: 'You have a much stronger argument for reject',
    _.youAreAbleToReviewNow: 'You are now able to visit the review section.',
    _.youArgue: 'You argue about',
    _.youAgreeWithThecounterargument: 'You agree with the counter-argument which says that',
}
