#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
TODO

.. codeauthor:: Tobias Krauthoff <krauthoff@cs.uni-duesseldorf.de
"""
from dbas.strings.keywords import Keywords as _


def get_en_dict():
    return en_lang


en_lang = {

    # _.signs: ['+', '*', '/', '-'],
    '0': 'zero', '1': 'one', '2': 'two', '3': 'three', '4': 'four',
    '5': 'five', '6': 'six', '7': 'seven', '8': 'eight', '9': 'nine', '+': 'plus', '-': 'minus',
    '*': 'times', '/': 'divided by',
    _.arguments: 'arguments',
    _.error: 'Error',
    _.iActuallyHave: 'I actually have',
    _.insertOneArgument: 'I have one argument:',
    _.insertDontCare: 'It is one argument and the system is wrongly interpreting it!',
    _.forgotInputRadio: 'You forgot to choose the right interpretation',
    _.needHelpToUnderstandStatement: 'We need your help to understand your statement!',
    _.setPremisegroupsIntro1: 'You have used \'and\' in your statement: ',
    _.setPremisegroupsIntro2: '. There are two ways this could be interpreted. Please help us by selecting the right interpretation:',
    _.attack: 'You disagreed with',
    _.support: 'You agreed with',
    _.premise: 'Premise',
    _.because: 'Because',
    _.moreAbout: 'More about',
    _.undermine: 'It is false that',
    _.support1: '',
    _.undercut1: 'It is false that',
    _.undercut2: 'and this is no good counter-argument',
    _.overbid1: 'It is false that',
    _.overbid2: 'and this is a good counter-argument',
    _.rebut1: 'It is right that',
    _.rebut2: ', but I have a better statement',
    _.oldPwdEmpty: 'Old password field is empty.',
    _.newPwdEmtpy: 'New password field is empty.',
    _.confPwdEmpty: 'Password confirmation field is empty.',
    _.newPwdNotEqual: 'New passwords are not equal',
    _.pwdsSame: 'Both entered passwords are equal.',
    _.oldPwdWrong: 'Your old password is wrong.',
    _.pwdChanged: 'Your password was changed',
    _.emptyName: 'Your name is empty!',
    _.emptyEmail: 'Your e-mail is empty!',
    _.emtpyContent: 'Your content is empty!',
    _.maliciousAntiSpam: 'Your anti-spam message is empty or wrong!',
    _.nonValidCSRF: 'CSRF-Token is not valid',
    _.name: 'Name',
    _.mail: 'Mail',
    _.phone: 'Phone',
    _.message: 'Message',
    _.messageDeleted: 'Message deleted',
    _.notification: 'Notification',
    _.notificationDeleted: 'Notification deleted',
    _.pwdNotEqual: 'Passwords are not equal',
    _.nickIsTaken: 'Nickname is taken',
    _.mailIsTaken: 'E-Mail is taken',
    _.mailNotValid: 'E-Mail is not valid',
    _.mailSettingsTitle: 'Enables/Disables e-mails',
    _.notificationSettingsTitle: 'Enables/Disables notifications',
    _.errorTryLateOrContant: 'An error occurred, please try again later or contact the author',
    _.accountWasAdded: 'Your account was added and you are now able to log in.',
    _.accountRegistration: 'D-BAS Account Registration',
    _.accountWasRegistered: 'Your account was successfully registered for this e-mail.',
    _.accoutErrorTryLateOrContant: 'Your account with the nick could not be added. Please try again or contact the author.',
    _.nicknameIs: 'Your nickname is: ',
    _.newPwdIs: 'Your new password is: ',
    _.dbasPwdRequest: 'D-BAS Password Request',
    _.antispamquestion: 'What is',
    _.defaultView: 'Default View', _.positions: 'Positions',
    _.labels: 'Labels', _.myStatements: 'My statements',
    _.supportsOnMyStatements: 'Supports', _.attacksOnMyStatements: 'Attacks',
    _.addATopic: 'Add a topic', _.pleaseEnterTopic: 'Please enter your topic here:',
    _.pleaseEnterShorttextForTopic: 'Please enter a short-text for your topic here:',
    _.pleaseSelectLanguageForTopic: 'Please select the language of the new discussion here:',
    _.editIssueViewChangelog: 'Edit Issues / View Changelog',
    _.editTitleHere: 'Please, edit the selected Title here:',
    _.editInfoHere: 'Please, edit the selected info here:', _.viewChangelog: 'View Changelog',
    _.editStatementHere: 'Please, edit the statement here:', _.save: 'Save',
    _.cancel: 'Cancel', _.submit: 'Submit', _.close: 'Close',
    _.urlSharing: 'Share your URL',
    _.urlSharingDescription: 'Please feel free to share this url:', _.warning: 'Warning',
    _.islandViewFor: 'Island View for', _.resumeHere: 'Resume here', _.aand: 'and',
    _.andor: 'and/or', _.addedEverything: 'Everything was added.',
    _.addStatementRow: 'Add another statement.', _.addTopic: 'Add a Topic',
    _.alreadyInserted: 'This is a duplicate and already there.',
    _.addPremisesRadioButtonText: 'Let me enter my reasons!',
    _.addArgumentsRadioButtonText: 'Let me enter my own statements!',
    _.argumentContainerTextIfPremises: 'You want to state your own reasons?',
    _.argumentContainerTextIfArguments: 'You want to state your own arguments?',
    _.addPremiseRadioButtonText: 'Let me enter my reason!',
    _.addArgumentRadioButtonText: 'Let me enter my own statement!',
    _.argumentContainerTextIfPremise: 'You want to state your own reason?',
    _.argumentContainerTextIfArgument: 'You want to state your own argument?',
    _.argumentContainerTextIfConclusion: 'What is your idea? What should we do?',
    _.argueAgainstPositionToggleButton: 'Or do you want to argue against a position? Please toggle this button:',
    _.argueForPositionToggleButton: 'Or do you want to argue for a position? Please toggle this button:',
    _.andIDoNotBelieveCounter: 'and I do not believe that this is a good counter-argument for',
    _.andIDoNotBelieveArgument: 'and I do not believe that this is a good argument for',
    _.andTheyDoNotBelieveCounter: 'and they do not believe that this is a good counter-argument for',
    _.andTheyDoNotBelieveArgument: 'and they do not believe that this is a good argument for',
    _.argumentFlaggedBecauseOfftopic: 'This argument was reported by a participant, because it probably is <strong>off topic of the discussion</strong>.',
    _.argumentFlaggedBecauseSpam: 'This argument was reported by a participant, because it probably is <strong>spam</strong>.',
    _.argumentFlaggedBecauseHarmful: 'This argument was reported by a participant, because it probably is <strong>inappropriate, harmful or abbusive</strong>.',
    _.argumentFlaggedBecauseOptimization: 'This argument was reported by a participant, because it probably <strong>needs optimization</strong>.',
    _.argumentFlaggedBecauseEdit: 'This argument was improved from a grammatical point of view.',
    _.alternatively: 'Alternatively', _.addArguments: 'Add arguments',
    _.addStatements: 'Add statements', _.addArgumentsTitle: 'Adds new arguments',
    _.acceptItTitle: 'Accept it...', _.acceptIt: 'Accept it...',
    _.asReasonFor: 'as reason for', _.argument: 'Argument',
    _.attackPosition: 'attack Position', _.at: 'at', _.assertion: 'assertion',
    _.accepting: 'accepting', _.attackedBy: 'You were attacked by',
    _.attackedWith: 'You\'ve attacked with', _.agreeBecause: 'I agree because ',
    _.andIDoBelieveCounterFor: 'and I do believe that this is a counter-argument for',
    _.andIDoBelieveArgument: 'and I do believe that this is an argument for',
    _.attitudeFor: 'Attitudes for',
    _.alreadyFlaggedByOthers: 'This argument was already reported by others!',
    _.alreadyFlaggedByYou: 'You have already reported this argument!',
    _.breadcrumbsStart: 'Start', _.breadcrumbsChoose: 'Multiple reasons for',
    _.breadcrumbsJustifyStatement: 'Why do you think that',
    _.breadcrumbsGetPremisesForStatement: 'Get premises',
    _.breadcrumbsMoreAboutArgument: 'More about',
    _.breadcrumbsReplyForPremisegroup: 'Reply for group',
    _.breadcrumbsReplyForResponseOfConfrontation: 'Justification of',
    _.breadcrumbsReplyForArgument: 'Reply for argument',
    _.butIDoNotBelieveCounterFor: 'but I do not believe that this is a counter-argument for',
    _.butIDoNotBelieveArgumentFor: 'but I do not believe that this is a argument for',
    _.butIDoNotBelieveCounter: 'but I do not believe that this is a counter-argument for',
    _.butIDoNotBelieveArgument: 'but I do not believe that this is a argument for',
    _.butIDoNotBelieveReasonForReject: 'but I do not believe that this is a reason for rejecting',
    _.butTheyDoNotBelieveCounter: 'but they do not believe that this is a good counter-argument for',
    _.butTheyDoNotBelieveArgument: 'but they do not believe that this is a good argument for',
    _.butOtherParticipantsDontHaveOpinionRegardingYourOpinion: 'but other participants do not have any opinion regarding your selection',
    _.butOtherParticipantsDontHaveArgument: 'but other participants do not have any argument for that.',
    _.butOtherParticipantsDontHaveCounterArgument: 'but other participants do not have any counter argument for that.',
    _.butWhich: 'but which one', _.but: 'but',
    _.butThenYouCounteredWith: 'But then you did not agree with this because',
    _.butYouCounteredWith: 'You did not agree with this because',
    _.butYouAgreedWith: 'And you agreed with this because',
    _.canYouGiveAReason: 'Can you give a reason?',
    _.canYouGiveAReasonFor: 'Can you give a reason for',
    _.canYouGiveACounter: 'Can you give a counter-argument?',
    _.canYouGiveACounterArgumentWhy1: 'Can you give a counter-argument, why are you against',
    _.canYouGiveACounterArgumentWhy2: '?',
    _.canYouGiveAReasonForThat: 'Can you give a reason for that?',
    _.clickHereForRegistration: 'Click <a data-toggle="modal" data-target="#popup-login" title="Login" data-href="login" >here</a> for log in or registration!',
    _.clickForMore: 'Click for more!', _.countOfArguments: 'Count of arguments',
    _.countOfPosts: 'Count of posts', _.confirmation: 'Confirmation', _.contact: 'Contact',
    _.contactSubmit: 'Submit your Message',
    _.confirmTranslation: 'If you change the language, your process on this page will be lost and you have to restart the discussion!',
    _.correctionsSet: 'Your correction was set.',
    _.checkFirstname: 'Better check your first name, because the input is empty!',
    _.checkLastname: 'Better check your last name, because the input is empty!',
    _.checkNickname: 'Better check your nickname, because the input is empty!',
    _.checkEmail: 'Better check your email, because the input is empty!',
    _.checkPassword: 'Better check your password, because the input is empty!',
    _.checkConfirmation: 'Better check the confirmation of your password, because the input is empty!',
    _.completeView: 'Complete View', _.completeViewTitle: 'Shows the complete graph',
    _.checkPasswordConfirm: 'Better check your passwords, because they are not equal!',
    _.clickToChoose: 'Click to choose', _.clearStatistics: 'Clear Statistics',
    _.currentDiscussion: 'Current discussion is about',
    _.description_undermine: 'This statement attacks the premise.',
    _.description_support: 'This statement supports the premise.',
    _.description_undercut: 'This statement attacks the justification (undercut). You do not believe that the premise justifies the conclusion.',
    _.description_overbid: 'This statement supports the justification (overbid). You do believe that the premise justifies the conclusion.',
    _.description_rebut: 'This statement is against the conclusion itself.',
    _.description_no_opinion: 'You just have no opinion regarding the confrontation or you just want to skip this.',
    _.decisionIndex7: 'Decision Index - Last 7 Days',
    _.decisionIndex30: 'Decision Index - Last 30 Days',
    _.decisionIndex7Info: 'Count of made decision (due to clicks in a discussion) in the last 7 days',
    _.decisionIndex30Info: 'Count of made decision (due to clicks in a discussion) in the last 30 days',
    _.dateString: 'Date', _.deleteTrack: 'Delete track',
    _.deleteStatement: 'Delete statement', _.deleteHistory: 'Delete history',
    _.delete: 'Delete', _.disagreeBecause: 'I disagree because ',
    _.dataRemoved: 'Data was successfully removed.',
    _.didYouMean: 'Top10 statements, which you probably could mean:',
    _.dialogView: 'Dialog View', _.dialogViewTitle: 'Show the dialog View',
    _.displayControlDialogGuidedTitle: 'Dialog View',
    _.displayControlDialogGuidedBody: 'You will never see something like an argumentation map, because the systems seems to be like a dynamic and generic.',
    _.displayControlDialogIslandTitle: 'Island View',
    _.displayControlDialogIslandBody: 'Okay, you want to see more as, but not everything. Therefore the island view will present you a list of every connected statement for an specific statement.',
    _.displayControlDialogExpertTitle: 'Expert View',
    _.displayControlDialogExpertBody: 'So, you think you are an expert? Okay, you can have a view of the complete argumentation map',
    _.displayControlDialogGraphTitle: 'Graph-View',
    _.displayControlDialogGraphBody: 'Presentation of the discusion as graph.',
    _.discussionEnd: 'The discussion ends here.',
    _.discussionEndLinkText: 'You can click <a id="discussionEndStepBack" data-href="back" onclick="window.history.back();" style="cursor: pointer;">here</a> to go one step back or you can use the button above or <a id="discussionEndRestart" data-href="restart" >this link</a> to restart the discussion.',
    _.discussionInfoTooltip1: 'The discussion was started',
    _.discussionInfoTooltip2: 'and already has', _.discussionInfoTooltip3sg: 'argument.',
    _.discussionInfoTooltip3pl: 'arguments.', _.duplicate: 'Duplikat',
    _.duplicateDialog: 'This textversion is deprecated, because it was already edited to this version.\nDo you want to set this version as the current one once again?',
    _.doesNotHold: 'does not hold', _.isNotRight: 'does not hold',
    _.doNotHesitateToContact: 'Do not hesitate to <span style="cursor: pointer;" id="contact-on-error"><strong>contact us (click here)</strong></span>',
    _.doesJustify: 'does justify that', _.doesNotJustify: 'does not justify that',
    _.doYouWantToEnterYourStatements: 'Do you want to enter your statement(s)?',
    _.dataAlreadyLockedByYou: 'You are already editing data. Please finish your work first!',
    _.dataAlreadyLockedByOthers: 'Sorry, this data edited by other participants.',
    _.earlierYouArguedThat: 'Earlier you argued that', _.editIndex: 'Edit Index - Last 30 Tage',
    _.editIndexInfo: 'Count of Edits',
    _.euCookiePopupTitle: 'This website is using cookies and Piwik.',
    _.euCookiePopupText: 'We use them to give you the best experience. If you continue using our website, we\'ll assume that you are happy to receive all cookies on this website and being tracked for academic purpose. All tracked data are saved anonymously with reduced masked IP-addresses.',
    _.euCookiePopoupButton1: 'Continue', _.euCookiePopoupButton2: 'Learn&nbsp;more',
    _.empty_news_input: 'News title or text is empty or too short!',
    _.empty_notification_input: 'Notification title or text is empty or too short!',
    _.email: 'E-Mail', _.emailWasSent: 'E-Mail was sent.',
    _.emailWasNotSent: 'E-Mail was not sent.',
    _.emailUnknown: 'The given mail address is unknown.',
    _.emailBodyText: 'This is an automatically generated mail by D-BAS https://dbas.cs.uni-duesseldorf.de/.\nFor contact please write an mail to krauthoff@cs.uni-duesseldorf.de\nThis system is part of a doctoral thesis and currently in an alpha-phase.',
    _.emailArgumentAddTitle: 'D-BAS Information about an Argument',
    _.emailArgumentAddBody: 'New statements were added to your argument. Have a look at:',
    _.error_code: 'Error code', _.edit: 'Edit', _.editTitle: 'Edit statement',
    _.feelFreeToLogin: 'If you want to proceed, please feel free to <u><a  data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">login</a></u> yourself :)',
    _.forText: 'for', _.forThat: 'accepting that',
    _.firstConclusionRadioButtonText: 'Let me enter my idea!',
    _.firstArgumentRadioButtonText: 'Let me enter my own statement(s)!',
    _.feelFreeToShareUrl: 'Please feel free to share this url', _.fetchLongUrl: 'Long URL',
    _.fetchShortUrl: 'Short URL', _.forgotPassword: 'Forgot Password',
    _.firstOneText: 'You are the first one, who said: ',
    _.firstOneInformationText: 'You are the first one, who is interested in: ',
    _.firstOneReason: 'You are the first one with this argument, please give a reason.',
    _.firstPositionText: 'You are the first one in this discussion!',
    _.firstPremiseText1: 'You are the first one, who said that',
    _.firstPremiseText2: 'Please enter your reason for your statement.',
    _.firstname: 'First name', _.fillLine: 'Please, fill this this line with your report',
    _.finishTitle: 'Leave the discussion!', _.fromm: 'from', _.gender: 'Gender',
    _.goBack: 'Click to go back', _.goHome: 'Go home', _.goStepBack: 'Go one step back',
    _.generateSecurePassword: 'Generate secure password',
    _.goodPointTakeMeBackButtonText: 'I agree, that is a good argument! Take me one step back.',
    _.group_uid: 'Group', _.goBackToTheDiscussion: 'Go back to the discussion',
    _.goForward: 'Click to go forward', _.haveALookAt: 'Hey, please have a look at ',
    _.hidePasswordRequest: 'Hide Password Request', _.hideGenerator: 'Hide Generator',
    _.hold: 'hold',
    _.howeverIHaveMuchStrongerArgumentRejectingThat: 'However, I have a much stronger argument for rejecting that',
    _.howeverIHaveMuchStrongerArgumentAcceptingThat: 'However, I have a much stronger argument for accepting that',
    _.howeverIHaveMuchStrongerArgument: 'However, I have a much stronger argument for',
    _.howeverIHaveEvenStrongerArgumentRejecting: 'However, I have an even stronger argument for rejecting that',
    _.howeverIHaveEvenStrongerArgumentAccepting: 'However, I have an even stronger argument for accepting that',
    _.imprint: 'Imprint', _.iAgreeWithInColor: 'I <span class=\'text-success\'>agree</span>',
    _.iAgreeWith: 'I agree ',
    _.iDisagreeWithInColor: 'I <span class=\'text-danger\'>disagree</span>',
    _.iDisagreeWith: 'I disagree', _.iDoNotKnow: 'I do not know',
    _.iDoNotKnowInColor: 'I <span class=\'text-info\'>do not know</span>',
    _.iHaveNoOpinionYet: 'I have no opinion yet about',
    _.iHaveNoOpinion: 'I have no opinion, show me an argument',
    _.iHaveNoOpinionYetInColor: 'I have <span class=\'text-info\'>no opinion yet</span>, show me an argument',
    _.informationForExperts: 'Information for experts',
    _.internalFailureWhileDeletingTrack: 'Internal failure, please try again or did you have deleted your track recently?',
    _.internalFailureWhileDeletingHistory: 'Internal failure, please try again or did you have deleted your history recently?',
    _.internalError: '<strong>Internal Error:</strong> Maybe the server is offline.',
    _.internalKeyError: 'Internal error while reading input data.', _.issueList: 'Topics',
    _.islandViewHeaderText: 'These are all arguments for: ', _.islandView: 'Island View',
    _.islandViewTitle: 'Shows the island View', _.irrelevant: 'Irrelevant',
    _.itIsTrueThat: 'it is true that', _.itIsTrue1: '', _.itIsTrue2: ' is true',
    _.itIsFalseThat: 'it is false that', _.itIsFalse1: '', _.itIsFalse2: 'is false',
    _.itTrueIsThat: 'it is true that', _.itFalseIsThat: 'it is false that',
    _.isFalse: 'is false', _.isNotAGoodIdea: 'is not a good idea',
    _.isNotAGoodIdeaInColor: '<span class=\'text-danger\'>is not a good idea</span>',
    _.isTrue: 'is true', _.areTrue: 'are true', _.initialPosition: 'Initial Position',
    _.initialPositionSupport: 'What is your initial position you are supporting?',
    _.initialPositionAttack: 'What is your initial position you want to attack?',
    _.initialPositionInterest: 'What is the initial position you are interested in?',
    _.invalidEmail: 'Your mail is invalid!',
    _.iAcceptCounter: 'and I do accept that this is a counter-argument for',
    _.iAcceptArgument: 'and I do accept that this is an argument for',
    _.iAcceptCounterThat: 'and I do accept that this is a counter-argument for',
    _.iAcceptArgumentThat: 'and I do accept that this is an argument for',
    _.iHaveMuchStrongerArgumentRejecting: 'I have a much stronger argument for rejecting that',
    _.iHaveEvenStrongerArgumentRejecting: 'I have an even stronger argument for rejecting that',
    _.iHaveMuchStrongerArgumentAccepting: 'I have a much stronger argument for accepting that',
    _.iHaveEvenStrongerArgumentAccepting: 'I have an even stronger argument for accepting that',
    _.iNoOpinion: 'I have no opinion regarding',
    _.interestingOnDBAS: 'Interesting discussion on DBAS', _.inputEmpty: 'Input is empty!',
    _.informationForStatements: 'Information for the statements',
    _.jumpAnswer0: 'Right, I support the XXCONCLUSIONXX and accept the XXPREMISEXX.',
    _.jumpAnswer1: 'Right, I support the XXCONCLUSIONXX, but I want to add my own XXPREMISEXX.',
    _.jumpAnswer2: 'Right, I support the XXCONCLUSIONXX, but the XXPREMISEXX does not support it.',
    _.jumpAnswer3: 'Wrong, the XXCONCLUSIONXX is false.',
    _.justLookDontTouch: 'Just look, do not touch anything!', _.keyword: 'Keyword',
    _.keywordStart: 'Start', _.keywordChooseActionForStatement: 'Choosing attitude',
    _.keywordGetPremisesForStatement: 'Getting premises',
    _.keywordMoreAboutArgument: 'More about',
    _.keywordReplyForPremisegroup: 'Reply for argument',
    _.keywordReplyForResponseOfConfrontation: 'Justification of',
    _.keywordReplyForArgument: 'Confrontation', _.keepSetting: 'Keep this', _.holds: 'holds',
    _.holdsInColor: '<span class=\'text-success\'>holds</span>',
    _.hideAllUsers: 'Hide all users', _.hideAllAttacks: 'Hide all attacks',
    _.letMeExplain: 'Let me explain it this way', _.levenshteinDistance: 'Levenshtein-Distance',
    _.languageCouldNotBeSwitched: 'Unfortunately, the language could not be switched',
    _.last_action: 'Last Action', _.last_login: 'Last Login', _.login: 'Login',
    _.logfile: 'Logfile for', _.letsGo: 'Click here to start now!',
    _.letsGoBack: 'Let\'s go back!', _.letsGoHome: 'Let\'s go home!',
    _.langNotFound: 'Language not found', _.more: 'More', _.medium: 'medium',
    _.minLength: 'Minimal length', _.myArgument: 'my argument', _.next: 'Next Entry',
    _.now: 'Now', _.newNotification: 'You got a new notification.',
    _.newMention: 'You are mentioned in a contribution.',
    _.newPremiseRadioButtonText: 'None of the above! Let me state my own reason!',
    _.newPremisesRadioButtonText: 'None of the above! Let me state my own reason(s)!',
    _.newPremiseRadioButtonTextAsFirstOne: 'Let me state my own reason!',
    _.newPremisesRadioButtonTextAsFirstOne: 'Let me state my own reason(s)!',
    _.newStatementRadioButtonTextAsFirstOne: 'Let me state my own statement!',
    _.newStatementsRadioButtonTextAsFirstOne: 'Let me state my own statement(s)!',
    _.newConclusionRadioButtonText: 'Neither of the above, I have a different idea!',
    _.newsAboutDbas: 'News about D-BAS', _.nickname: 'Nickname',
    _.noOtherAttack: 'The system has no other counter-argument',
    _.noIslandView: 'Could not fetch data for the island view. Sorry!',
    _.noCorrections: 'No corrections for the given statement could be fetched.',
    _.noCorrectionsSet: 'Correction could not be set, because your user was not fount in the database. Are you currently logged in?',
    _.noDecisionDone: 'No decision was done.',
    _.notInsertedErrorBecauseEmpty: 'Your idea was not inserted, because your text is too short or empty.',
    _.notInsertedErrorBecauseDuplicate: 'Your idea was not inserted, because your idea is a duplicate.',
    _.notInsertedErrorBecauseUnknown: 'Your idea was not inserted due to an unknown error.',
    _.notInsertedErrorBecauseInternal: 'Your idea was not inserted due to an internal error.',
    _.noEntries: 'No entries', _.noTrackedData: 'No data was tracked.', _.number: 'No',
    _.note: 'Note', _.no_entry: 'No entry', _.no_arguments: 'No arguments for this opinion',
    _.noRights: 'You have no rights for this action!', _.notLoggedIn: 'You are not logged in.',
    _.on: 'On', _.off: 'Off', _.opinion: 'the opinion',
    _.onlyOneItem: 'If you want to state a new reason, please click here to log in.',
    _.onlyOneItemWithLink: 'If you want to state a new reason, please click <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">here</a> to log in.',
    _.unfortunatelyOnlyOneItem: 'Unfortunately you only have one option to choose. If you want to state a new reason, please click <a data-href="login" data-toggle="modal" data-target="#popup-login" title="Login">here</a> to log in.',
    _.otherParticipantsConvincedYouThat: 'Other participants convinced you that',
    _.otherParticipantsThinkThat: 'Other participants think that',
    _.otherParticipantsAgreeThat: 'Other participants agree that',
    _.otherParticipantsDontHaveOpinion: 'Other participants do not have any opinion regarding',
    _.otherParticipantsDontHaveOpinionRegaringYourSelection: 'Other participants do not have any opinion regarding your selection',
    _.otherParticipantsDontHaveCounterForThat: 'Other participants do not have any counter-argument for that',
    _.otherParticipantsDontHaveNewCounterForThat: 'Other participants do not have any new counter-argument for that. You already have seen all other counter-arguments.',
    _.otherParticipantsDontHaveCounter: 'Other participants do not have any counter-argument for ',
    _.otherParticipantsDontHaveArgument: 'Other participants do not have any argument for ',
    _.otherParticipantsAcceptBut: 'Other participants accept your argument, but',
    _.otherParticipantDisagreeThat: 'Other participants disagree that ',
    _.otherUsersClaimStrongerArgumentRejecting: 'Other participants claim to have a stronger statement for rejecting',
    _.otherUsersClaimStrongerArgumentAccepting: 'Other participants claim to have a stronger statement for accepting',
    _.otherUsersHaveCounterArgument: 'Other participants have the counter-argument that',
    _.otherUsersSaidThat: 'Other participants said that',
    _.opinionBarometer: 'Opinion Barometer',
    _.pleaseAddYourSuggestion: 'Please add your suggestion!',
    _.premiseGroup: 'PremiseGroup',
    _.previous: 'Previous Entry',
    _.publicNickTitle: 'Enables/Disables the real nickname on your public page.',
    _.passwordSubmit: 'Change Password',
    _.preferedLangTitle: 'Preferred language for all notifications/mails',
    _.priv_access_opti_queue: 'Access to the optimization queue',
    _.priv_access_del_queue: 'Access to the delete queue',
    _.priv_access_edit_queue: 'Access to the edit queue',
    _.priv_history_queue: 'Access to all reviews of the past',
    _.publications: 'Publications',
    _.queueDelete: 'Deletes',
    _.queueOptimization: 'Optimizations',
    _.queueEdit: 'Edits',
    _.queueHistory: 'History',
    _.queueOngoing: 'Ongoing',
    _.myPosition: 'my point of view',
    _.the_der: 'the',
    _.the_die: 'the',
    _.the_das: 'the',
    _.theirPosition: 'their point of view',
    _.registered: 'Registered',
    _.restartDiscussion: 'Restart Discussion',
    _.restartDiscussionTitle: 'Restart Discussion',
    _.restartOnError: 'Please try to reload this page or restart the discussion, if reloading does not fix the problem.',
    _.recipient: 'Recipient',
    _.recipientNotFound: 'Recipient not found!',
    _.reference: 'Referenz',
    _.report: 'Report',
    _.reportStatement: 'Report statement',
    _.reportArgument: 'Report argument',
    _.review: 'Review',
    _.review_history: 'Review History',
    _.review_ongoing: 'Current Reviews',
    _.right: 'Right',
    _.reason: 'Reason',
    _.requestTrack: 'Request track',
    _.refreshTrack: 'Refresh track',
    _.requestHistory: 'Request history',
    _.refreshHistory: 'Refresh history',
    _.requestFailed: 'Request failed',
    _.rejecting: 'rejecting',
    _.remStatementRow: 'Removes this row.',
    _.reaction: 'Reactions',
    _.reactionFor: 'Reactions for',
    _.rep_reason_first_argument_click: 'You choose your first argument.',
    _.rep_reason_first_confrontation: 'You survived your first confrontation',
    _.rep_reason_first_position: 'You entered a new position for the first time',
    _.rep_reason_first_justification: 'You entered a new justification for the first time',
    _.rep_reason_first_new_argument: 'You entered a new argument for the first time',
    _.rep_reason_new_statement: 'For any argument you entered after your first one',
    _.rep_reason_success_flag: 'You set your first flag',
    _.rep_reason_success_edit: 'You send your first edit',
    _.rep_reason_bad_flag: 'You misused the flag function',
    _.rep_reason_bad_edit: 'You made a bad edit',
    _.questionTitle: 'Get more information about the statement!',
    _.saveMyStatement: 'Save my Statement!',
    _.selectStatement: 'Please select a statement!',
    _.showAllUsers: 'Show all users',
    _.showAllArguments: 'Show all arguments',
    _.showAllArgumentsTitle: 'Show all arguments, done by users',
    _.showAllUsersTitle: 'Show all users, which are registered',
    _.supportPosition: 'support position',
    _.supportsNot: 'does not support',
    _.isupport: 'I support',
    _.strength: 'Strength',
    _.strong: 'strong',
    _.strongerStatementForAccepting1: 'but they claim to have a stronger statement for ',
    _.strongerStatementForAccepting2: 'accepting',
    _.strongerStatementForAccepting3: '',
    _.strongerStatementForRecjecting1: 'but they claim to have a stronger statement for ',
    _.strongerStatementForRecjecting2: 'rejecting',
    _.strongerStatementForRecjecting3: '',
    _.soYouEnteredMultipleReasons: 'So you entered multiple reasons',
    _.soYourOpinionIsThat: 'So your opinion is that',
    _.soYouWantToArgueAgainst: 'So you want to counter-argue against',
    _.shortenedBy: 'which was shortened with',
    _.shareUrl: 'Share Link',
    _.showMeAnotherArgument: 'Show me another argument',
    _.soThatOtherParticipantsDontHaveOpinionRegardingYourOpinion: 'so that participants do not have any opinion regarding your selection',
    _.switchDiscussion: 'Change the discussion\'s topic',
    _.switchDiscussionTitle: 'Switch Discussion',
    _.switchDiscussionText1: 'If you accept, you will change the topic of the discussion to',
    _.switchDiscussionText2: 'and the discussion will be restarted.',
    _.switchLanguage: 'Switch Language',
    _.statement: 'Statement',
    _.statementAdded: 'Statement was added',
    _.statementIsAbout: 'Statement ist about added',
    _.argumentAdded: 'Argument was added',
    _.statementAddedMessageContent: 'Hey, someone has added his/her opinion regarding your argument!',
    _.argumentAddedMessageContent: 'Hey, someone has added his/her argument regarding your argument!',
    _.statementIndex: 'Statement Index - Last 30 Days',
    _.statementIndexInfo: 'Count of added Statements',
    _.sureThat: 'I\'m reasonably sure that ',
    _.surname: 'Surname',
    _.myStatement: 'my statement',
    _.showMeAnArgumentFor: 'Show me an argument for',
    _.textAreaReasonHintText: 'Please use a new text area for every reason, write short and clear!',
    _.theCounterArgument: 'the counter-argument',
    _.therefore: 'Therefore',
    _.thinkWeShould: 'I think we should ',
    _.track: 'Track',
    _.this: 'this',
    _.textversionChangedTopic: 'Statement was edited',
    _.textversionChangedContent: 'Your original statement was edited by',
    _.to: 'to',
    _.history: 'History',
    _.topicString: 'Topic',
    _.text: 'Text',
    _.theySay: 'They say',
    _.theyThink: 'They think',
    _.thisIsACopyOfMail: 'This is a copy of your mail',
    _.thisConfrontationIs: 'This confrontation is a',
    _.theirArgument: 'their argument',
    _.thisArgument: 'this argument',
    _.textChange: 'Some statement of yours was edited.',
    _.thxForFlagText: 'Thanks for reporting, we will have a look at it!',
    _.veryweak: 'very weak',
    _.wantToStateNewPosition: 'If you want to state a new position, please click here to log in.',
    _.weak: 'weak',
    _.wrong: 'Wrong',
    _.where: 'Where',
    _.wouldYourShareArgument: 'Would you share your argument?',
    _.whatDoYouThinkAbout: 'What do you think about',
    _.whatDoYouThinkOf: 'What do you think of',
    _.whatDoYouThinkAboutThat: 'What do you think about that',
    _.whatIsYourIdea: 'What is your idea / opinion? What should we do?',
    _.whatIsYourMostImportantReasonFor: 'What is your most important reason for',
    _.whatIsYourMostImportantReasonWhyFor: 'What is your most important reason why',
    _.whatIsYourMostImportantReasonWhyAgainst: 'What is your most important reason why',
    _.whatIsYourMostImportantReasonWhyForInColor: 'What is your most important reason why',
    _.whatIsYourMostImportantReasonWhyAgainstInColor: 'What is your most important reason why',
    _.whyDoYouThinkThat: 'Why do you think that',
    _.wrongURL: 'Your URL seems to be wrong.',
    _.whyAreYouDisagreeingWith: 'Why are you disagreeing with',
    _.whyAreYouAgreeingWith: 'Why are you agreeing with',
    _.whyAreYouDisagreeingWithInColor: 'Why are you <span class=\'text-danger\'>disagreeing</span> with',
    _.whyAreYouAgreeingWithInColor: 'Why are you <span class=\'text-success\'>agreeing</span> with',
    _.whyAreYouDisagreeingWithThat: 'Why are you disagreeing with that?',
    _.youMadeA: 'You made a',
    _.youMadeAn: 'You made an',
    _.relation_undermine: 'is a counter-argument for',
    _.relation_support: 'is a reason for',
    _.relation_undercut: 'is a counter-argument for',
    _.relation_overbid: 'is a reason for',
    _.relation_rebut: 'is a counter-argument for',
    _.uid: 'ID',
    _.unfortunatelyNoMoreArgument: 'Unfortunately there are no more arguments about',
    _.userPasswordNotMatch: 'User / Password do not match',
    _.userOptions: 'Users Options',
    _.userNotFound: 'User not found',
    _.userIsNotAuthorOfStatement: 'You are not the author of this statement',
    _.userIsNotAuthorOfArgument: 'You are not the author of this argument',
    _.voteCountTextFirst: 'You are the first one with this opinion',
    _.voteCountTextMayBeFirst: 'You would be the first one with this opinion',
    _.voteCountTextOneOther: 'One other participant with this opinion',
    _.voteCountTextMore: 'more participants with this opinion',
    _.visitDeleteQueue: 'Visit the delete queue of D-BAS.',
    _.visitDeleteQueueLimitation: 'You need at least XX reputation points to review deletes.',
    _.visitEditQueue: 'Visit the edit queue of D-BAS.',
    _.visitEditQueueLimitation: 'You need at least XX reputation points to review edits.',
    _.visitOptimizationQueue: 'Visit the optimization queue of D-BAS.',
    _.visitOptimizationQueueLimitation: 'You need at least XX reputation points to review optimizations.',
    _.visitHistoryQueue: 'Visit the history of reviews of D-BAS.',
    _.visitHistoryQueueLimitation: 'You need at least XX reputation points to have a look into the past.',
    _.visitOngoingQueue: 'Visit the current ongoing reviews of D-BAS.',
    _.welcome: 'Welcome',
    _.welcomeMessage: 'Welcome to the novel dialog-based argumentation system.<br>We hope you enjoy using this system and happy arguing!',
    _.youAreInterestedIn: 'You are interested in',
    _.youAgreeWith: 'You agree with',
    _.youDisagreeWith: 'You disagree with',
    _.youSaidThat: 'You said that',
    _.youUsedThisEarlier: 'You used this earlier',
    _.youRejectedThisEarlier: 'You rejected this earlier',
    _.youHaveMuchStrongerArgumentForAccepting: 'You have a much stronger argument for accepting',
    _.youHaveMuchStrongerArgumentForRejecting: 'You have a much stronger argument for rejecting',
    # _.insertDontCare = 'I don’t care about this, leave me alone and take my statement as it is!'

}
